### ISSUE TITLE
Start list of protocols and platform dialects to describe

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-binding-templates#1]
We need a list of protocols that serves as input to find the vocabulary needed to have protocol binding descriptions. The list items should be prioritized in the sense where to begin; this should be based on the available information and experts to help. Overall, this will be related to the liaisons W3C WoT has.

Initial (unsorted) list to be extended:
* ("vanilla") HTTP
* ("vanilla") CoAP
  * CoAP
  * CoAP-over-TCP
  * CoAP-over-WebSockets
* OCF
  * OCF CoAP
* oneM2M
  * oneM2M HTTP
  * oneM2M CoAP
  * oneM2M MQTT
  * oneM2M WebSockets
* ("vanilla") MQTT (lets use MQTT5, since previous versions do not provide the facilities required for open, WoT-like systems (e.g., no headers for Media Type etc.)
* OPC UA
  * UA-Binary over TCP

**Comment by zhangyongjing** [comment]
Note that oneM2M also has WebSocket binding, but we could put it in the parking lot for the time being. I suggest to start with HTTP and CoAP.

**Comment by mkovatsc** [comment]
Thanks for the comment; let's still put them on the list (updated post).

**Comment by mmccool** [comment]
Could add Mozilla proposal to list.   While the basic REST web interface should be straightforward, the WebSocket interface may need a little more focus.

**Comment by mjkoster** [comment]
Current strawman list from recent discussions:
- Simple CoAP 
- Simple HTTP 
- Events using websocket protocol
- Events using MQTT 
- Events using EventSource 
- OCF flavor of CoAP
- LWM2M flavor of CoAP
- Bindings for Interconnected Servient use case

**Comment by draggett** [comment]
WebSockets are useful for properties, actions, events and metadata updates, i.e. you should drop "Events using " before "websocket protocol".

**Comment by mmccool** [comment]
Echonet/BACnet

**Comment by mmccool** [comment]
use cases for pub-sub pattern (or eventing):
- sleeping devices (power constrained devices)
- reactive design pattern (software engineering)
- low latency response (real time systems)
- lossy events
- loose coupling, especially with named topics (reader and writer are not directly connected)
- broadcast pattern (one source, many sources)
- confluence pattern (many sources, one reader)
- privacy (with named topics) - loose coupling, reader/writer do not know about each other
- streaming (producer, not reader, controls timing) - writer has little memory, can't buffer indefinitely

**Comment by mmccool** [comment]
also important that we look at industrial use cases, especially where it breaks assumptions of home use cases

**Comment by egekorkan** [comment]
I will be closing this issue and moving the discussion to #92. Currently, the following protocols from the https://github.com/w3c/wot-binding-templates/issues/1#issuecomment-323921856 are done already:
- Simple CoAP
- Simple HTTP
- Events using MQTT
