### ISSUE TITLE
Observable Properties

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-binding-templates#10]
The concept of Observable Properties is already in the TD Editor's Draft and might end up in the Scripting API Editor's Draft soon. However, it is still completely open, how this should work on the protocol level.

For CoAP and some HTTP extensions, a single entry could work in the protocol binding:
```json
"link": {
    "href": "coaps://mytemp.example.com/temp",
    "mediaType": "application/json",
    "http:methodName": "get",
    "observe": "coap:observe"
}
```
or `"observe": "http:longpoll"`.

If reading the Property works through HTTP, but observing through WebSockets, we have a problem. Question is, if this case should even be in scope. A Thing providing this has to implement two different kind of interaction mechanisms anyway, so it could also simply model this as two Interactions: one normal Property and one Event.

Thoughts?

**Comment by mkovatsc** [comment]
During the Burlingame 2017 PlugFest the notion of using the `rel` attribute came up and it would look like this:

```javascript
"link": [
  {
    "href": "coaps://mytemp.example.com/temp",
    "mediaType": "application/json",
    "rel": "read",
    "http:methodName": "get"
  },
  {
    "href": "coaps://mytemp.example.com/temp",
    "mediaType": "application/json",
    "rel": "observe",
    "http:methodName": "get",
    "http:messageHeader": [
      {
        "http:fieldName": 6, // Observe option
        "http:fieldValue": 1
      },
  }
]
```

**Comment by mjkoster** [comment]
Here is an example including the proposed "form" tag and a more realistic CoAP vocabulary, following the style of http in RDF

```
"form": [
  {
    "href": "coaps://mytemp.example.com/temp",
    "rel": "observe",
    "coap:methodName": "GET",
    "coap:methodCode": "0.01",
    "coap:mthd": "http://www.w3.org/xxxx/coap-methods#GET",
    "coap:MessagelHeader": [
      {
        "coap:hdrName": "http://www.w3.org/xxxx/coap-headers#accept",
        "coap:fieldName": "Accept",
        "coap:fieldCodeNumber": 17,
        "coap:fieldValue": 10000
      },
      {
        "coap:hdrName": "http://www.w3.org/xxxx/coap-headers#ocf-accept-version",
        "coap:fieldName": "OCF-Accept-Content-Format-Version",
        "coap:fieldCodeNumber": 2049,
        "coap:fieldValue": "1.1.0"
      },
      {
        "coap:hdrName": "http://www.w3.org/xxxx/coap-headers#observe",
        "coap:fieldName": "Observe",
        "coap:fieldCodeNumber": 6,
        "coap:fieldValue": 0
      }
    ]
```

**Comment by mkovatsc** [comment]
See unified example in #13 . Closing.
