### ISSUE TITLE
How to propose a new binding + TD example 

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-binding-templates#103]
What is currently missing is to provide a clear guideline what you have to do to propose a new binding for WoT. What are the mandatory processes? E.g., with a chat with @egekorkan, there should be something like:

>A protocol binding for WoT TD MUST be able to map WoT operation types (readproperty, invokeaction, etc.) to concrete protocol methods. In addition, the binding should use or propose a URI scheme to identify the protocol.

Concrete examples + TD snippet would be great.

**Comment by sebastiankb** [comment]
Based on the discussion in the last TD call, we should evaluate if we restructure the Binding Document. At the moment different places are used to provide protocol specific information, e.g., for HTTP Example 20&21, Section 5.3.1 and Annex A. 

I think, it makes sens to put all relevant information of a protocol in one section that follow a same sub-section structure (e.g., one for URI protocol scheme, usage context namespace, etc) to get the relevant information. --> Option A

Alternative can be that we use the binding document for a generic document to define the WoT binding principle and use related sub-documents (as W3C Note?) to specify the concrete protocol for a WoT binding. A good example for this could be the RFC for [Uniform Resource Locator](https://de.wikipedia.org/wiki/Uniform_Resource_Locator) which has a Generic Syntax document and a couple related documents for different protocol usage. --> Option B

What do you think about this and which option do you would prefer?

**Comment by egekorkan** [comment]
In both cases, I like that protocols are well contained. I prefer the second option since it would also allow for each protocol to have different editors.

**Comment by egekorkan** [comment]
This will be done as the result of #113 . Closing in order to continue discussion there.
