### ISSUE TITLE
Splitting the Main Document

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-binding-templates#113]
This was discussed in multiple calls but there wasn't a concrete place to discuss it yet. We want to restructure the document into smaller sub documents. The current sub-document categories are:
1. Mapping to different communication protocols: HTTP, CoAP, MQTT, Modbus
2. Mapping to different media types: XML, JSON, binary
3. Mapping to different platforms: ECHONET, OPC-UA

Some requirements for all these documents (partially my opinion):
1. Each document have different dates
2. Each document can have different authors
3. Each document has a small informative introduction.
4. Each document has best practices, i.e. if you are using this protocol/platform, we recommend you to write a TD like the following
5. (When applicable) Each document has an associated ontology

Please comment below for what other requirements could be.

**Comment by danielpeintner** [comment]
This looks like a _multidimensional_ selection out of protocol (sub-protocol?), mediaType (and platform).

@egekorkan do you already have an idea in mind how this could look like document-wise?

**Comment by egekorkan** [comment]
Good point ;) So ideally this would be for brownfield devices. 

If the devices are part of a platform that dictates the use of a certain protocol and media type, the reader/developer of these devices should not look into other parts than the platform specification. For example, if I want to make Philips Hue devices WoT compatible, I should not look into HTTP protocol document but into Philips Hue only, even though that Philips Hue uses HTTP. 

If someone has built a custom HTTP/CoAP/MQTT device with myWonderfulLibrary, they can simply look into the protocol-specific document. The media types should be chosen on top of the protocol anyways most of the time. Some protocols are not flexible to use different media types (like Modbus). In those cases, the protocol document should include how the media type is represented. This would be analogous to how a platform dictates the use of a certain protocol and media type but one less constraint.

**Comment by egekorkan** [comment]
The changes are being tracked in restructuring branch
