### ISSUE TITLE
No default HTTP vocabulary for observable properties and events

### ISSUE THREAD

**Issue by JKRhb** [w3c/wot-binding-templates#114]
I noticed that there is currently no default vocabulary for events and observable properties in the [HTTP Default Vocabulary Terms](https://w3c.github.io/wot-binding-templates/#http-default-vocabulary-terms) table. Looking into the [source code](https://github.com/w3c/wot-binding-templates/blob/main/index.html#L1437-L1464) I noticed that there is an existing vocabulary which is, however, commented out at the moment.

Is this intentional and HTTP is not supposed to be used for these kinds of operation at the moment? Or could the mentioned lines of code be moved back into the document?

**Comment by egekorkan** [comment]
I am not super sure about the reason but I remember commenting it out. Probably, it was due to the fact we cannot recommend a certain default value when eventing is rather loosely done/defined in HTTP

**Comment by JKRhb** [comment]
> I am not super sure about the reason but I remember commenting it out. Probably, it was due to the fact we cannot recommend a certain default value when eventing is rather loosely done/defined in HTTP

I see, that makes sense! Hmm, maybe the following paragraph in [section 5.3](https://w3c.github.io/wot-binding-templates/#protocol-vocabulary) should be adjusted then:

> The protocol vocabularies for each protocol are presented as two tables per protocol. The first table details the vocabulary terms, whereas the second one lists a default mapping of the op for the given protocol, if that op value is defined for the given protocol.

As no default values are given it implies that observing/subscribing to events is generally not possible with HTTP.

**Comment by egekorkan** [comment]
So after a quick discussion with others offline, I am thinking of adding a `Possible Mappings` section for each protocol. There, each WoT operation type will be listed with possible protocol methods that can be used for this operation. This should be written in an informative but strongly recommending it. It should be still possible to use HTTP POST for reading a property but the possible mapping should not include it.

**Comment by JKRhb** [comment]
> So after a quick discussion with others offline, I am thinking of adding a `Possible Mappings` section for each protocol. There, each WoT operation type will be listed with possible protocol methods that can be used for this operation. This should be written in an informative but strongly recommending it. It should be still possible to use HTTP POST for reading a property but the possible mapping should not include it.

Sounds good :) Would this be an addition to the defaults that have been specified so far?

**Comment by egekorkan** [comment]
I would propose to close this since the discussion will probably take place in #199 and #203

**Comment by JKRhb** [comment]
I agree, closing this issue since the tables mentioned above have been added to the documents :)
