### ISSUE TITLE
Modbus Prefix

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-binding-templates#119]
In the [Modbus document](https://w3c.github.io/wot-binding-templates/bindings/modbus/) we use two different prefixes
* `modbus`, e.g., in [Form terms](https://w3c.github.io/wot-binding-templates/bindings/modbus/index.html#form-terms)
* `modv`, e.g., in [Entity](https://w3c.github.io/wot-binding-templates/bindings/modbus/index.html#entity) 

There is some kind of mixed usage in the entire document. I think we should agree on **one** prefix.

**Comment by egekorkan** [comment]
@relu91 I guess it should be modv right?

**Comment by relu91** [comment]
Actually, I prefer `modbus`, `modv` (modbus vocabulary) is an odd abbreviation IMO. Plus it is also weird within the context of Liked Data community where prefixes usually follows the name of the ontology (e.g., `sosa`, `ssn`, `schema`, etc.)

**Comment by danielpeintner** [comment]
I agree `modv` is somewhat clumsy. On the other hand it matches with what we have done in the past with `htv`, `cov`, `mqv`, ...

**Comment by relu91** [comment]
> I agree `modv` is somewhat clumsy. On the other hand it matches with what we have done in the past with `htv`, `cov`, `mqv`, ...
> 
> EDIT: In the same spirit it *should* be even `mov` or `mbv ` ?

indeed since we are refactoring I would change them too. Is it troublesome?

**Comment by egekorkan** [comment]
TD call 22.11: We decided already at #129 to change the prefix but it got lost. the prefix for modbus can be `modv` so that it is clear that it is not m-bus.
The main document needs to be updated since there is an example with that.
