### ISSUE TITLE
Links becoming Web Forms

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-binding-templates#12]
After more complexity was pushed down to the Protocol Bindings, the `link` elements became quite verbose. The carry a lot of information about how to construct the request, so that they are rather Web forms than Web links!

Thus my proposal: Rename the `link` element of Interactions to `form`, which frees up the term `link` to be used to list the relations of this Thing to other Things (the Web links to other Things).

**Comment by mjkoster** [comment]
Agreed.

Will rework the examples to change to "form" and consider adding the "link" construct to illustrate the difference.

**Comment by mkovatsc** [comment]
Made example in #13 and triggered TD TF. Closing.
