### ISSUE TITLE
uriVariables in bindings

### ISSUE THREAD

**Issue by tuve** [w3c/wot-binding-templates#126]
To me it is a bit unclear if uriVariables can be used in protocol bindings. The name suggest they are for the uri (href) but it would make sense to have them applicable to protocol bindings as well (and possible rename/alias them).

imaginary example

```
"forms": [
    {
        "op": "observeproperty",
        "href": "lvm2m://deviceendpoint/3003/0",
        "uriVariables": {
            "pmin": { "type": "number", "description": "Min time in seconds between updates if a value has changed" },
            "pmax": { "type": "number", "description": "Max time in seconds between updates even if no value has changed" }
        },
        "lwm2mv:op": "observe",
        "lwm2mv:pmin": "{pmin}",
        "lwm2mv:pmin": "{pmax}"
    },

```

**Comment by egekorkan** [comment]
This proposal also makes sense. This is currently not allowed but what you can do is put uriVariables in data schema level and then put their template in the corresponding href in the forms level.

**Comment by tuve** [comment]
Maybe the example above is a bit of a stretch since when using coap as transport in lwm2m pmin and pmax are actually uri variables. But I still it would be useful to be able to have something more generic like formVariables.

`/{Object ID}/{Object Instance ID}/{Resource ID}?pmin={minimum period}&pmax={maximum period}&gt={greater than}&lt={less than}&st={step}`

**Comment by egekorkan** [comment]
Sorry about the late reply. I didn't have my computer with me for quite some time to write more verbose examples/explanations. Here is the example from the spec that has uriVariables (aka query parameters, the part after the ? in a URI) and not uriTemplates (changing the uri resource).

```js
"properties": {
        "weather": {
            ...
            "uriVariables": {
                "lat": { "type": "number", "minimum": 0, "maximum": 90, "description": "Latitude for the desired location in the world" },
                "long": { "type": "number", "minimum": -180, "maximum": 180, "description": "Longitude for the desired location in the world" }
            },
            "forms": [{
              "href": "http://example.org/weather/{?lat,long}",
              "htv:methodName": "GET"
            }]
        },
```

The example you have put above can be done very similarly, i.e.:

```js
{
       ...
	"properties": {
		"myProperty": {  // you didn't specify the afffordance name
			"uriVariables": {
				"pmin": {
					"type": "number",
					"description": "Min time in seconds between updates if a value has changed"
				},
				"pmax": {
					"type": "number",
					"description": "Max time in seconds between updates even if no value has changed"
				}
			},
			"forms": [{
				"op": "observeproperty",
				"href": "lvm2m://deviceendpoint/3003/0/{?pmin,pmax}",
				"lwm2mv:op": "observe",
				"lwm2mv:pmin": "{pmin}", // this is out of the scope of the spec
				"lwm2mv:pmax": "{pmax}"
			}]
		}
	}
}
```

Could you provide an example with actual requests and responses. Also, from the example I have a feeling that you want to template the URIs as well that should actually be modeled as different affordances in WoT.

**Comment by tuve** [comment]
As of now I think I can manage with uriVariables as in your example. I would like to be able to model the uri itself with variables. But maybe that should be a topic of its own, since the use case for that is composition (and not inheritance) of thing models into a thing description. Basically having forms and href with variables and/or relative hrefs in a model such that a model can be reused with forms in a td. Again lwM2M is a use case where the multiple and individually addressable instances of the same object specification is possible.

**Comment by egekorkan** [comment]
I hadn't understood that you were intending to use TMs. If that is indeed the case, the following example of the TD spec shows how to use uri templates:
https://w3c.github.io/wot-thing-description/#example-56

**Comment by tuve** [comment]
Thank you
