### ISSUE TITLE
Broken links in the HTTP document

### ISSUE THREAD

**Issue by JKRhb** [w3c/wot-binding-templates#128]
After the restructuring of the document the image links in the HTTP document seem broken (see [here](https://w3c.github.io/wot-binding-templates/bindings/protocols/http/index.html#property-interactions)).

**Comment by danielpeintner** [comment]
Note: there are more of this tiny little things that need to be fixed.. 
e.g., broken links like to "XML Schema Binding" in https://w3c.github.io/wot-binding-templates/#content-types

**Comment by egekorkan** [comment]
Sorry about that. I will provide the fix directly without a PR

**Comment by egekorkan** [comment]
Now fixed :) 

Propose closing
