### ISSUE TITLE
Consider removing section 2.2 HTTP Default Vocabulary Terms

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-binding-templates#135]
Consider removing section [2.2 HTTP Default Vocabulary Terms](https://w3c.github.io/wot-binding-templates/bindings/protocols/http/index.html#http-default-vocabulary-terms) from HTTP Binding Template document. See https://github.com/w3c/wot/issues/996#issuecomment-957635696

**Comment by egekorkan** [comment]
I would not oppose this. There should however be a text saying/linking where they are defined since all protocol bindings declare these default bindings. This means that we should first decide where it should be, i.e. core profile or TD.

**Comment by mlagally** [comment]
I think it would be beneficial to clarify what we mean with "default". When is the default applied? What happens if somebody does not use the default?
The Profile goes beyond the notion of a "default" - it makes definitive choices of the protocol verbs for HTTP.

**Comment by benfrancis** [comment]
@mlagally wrote:
> I think it would be beneficial to clarify what we mean with "default".

From WoT Thing Description section [8.3.1 Protocol Binding based on HTTP](https://w3c.github.io/wot-thing-description/#http-binding-assertions):

>> To interact with a Thing that implements the Protocol Binding based on HTTP, a Consumer needs to know what HTTP method to use when submitting a form. In the general case, a Thing Description can explicitly include a term indicating the method, i.e., htv:methodName. For the sake of conciseness, the Protocol Binding based on HTTP defines Default Values for the operation types listed below, which also aims at convergence of the methods expected by Things (e.g., GET to read, PUT to write). _When no method is indicated in a form representing an Protocol Binding based on HTTP, a Default Value MUST be assumed as shown in the following table._ 

> When is the default applied?

When parsing the Thing Description.

> What happens if somebody does not use the default?

If an HTTP method is not explicitly provided in a Form and a Consumer does not apply the default, then the Consumer will be unable to use that interaction affordance.

> The Profile goes beyond the notion of a "default" - it makes definitive choices of the protocol verbs for HTTP.

I agree, the way I see the Core Profile is that it builds upon the default HTTP verbs defined in WoT Thing Description (and WoT Protocol Binding Templates) to prescribe additional details about how a conforming Consumer should interact with a Thing, without needing to include all of those details in the Thing Description.

**Comment by egekorkan** [comment]
I think we can revisit this but given the plans to remove the HTTP binding from the TD spec in the 2.0 version by making these documents normative, this has to stay here. I would thus propose to close it.

**Comment by egekorkan** [comment]
Call of 05.04: We have decided long ago to have individual bindings with default term sections. Closing.
