### ISSUE TITLE
Formalize the concept of `Data Schema Values`. 

### ISSUE THREAD

**Issue by relu91** [w3c/wot-binding-templates#141]
As introduced in #140, it is beneficial to have a formal model to refer to when explaining a [Payload Format Binding](https://w3c.github.io/wot-binding-templates/#creating-a-new-payload-format-binding). The problem is that in the Thing Description specification we have a model to describe the **schema** but not the **values** that should conform to this schema. To solve this issue we might have a one-liner definition in the Binding Template specification:
```
A Data Schema Value is anything that is valid for any of the defined DataSchemas
```

Or we can refer to already existing Web platform type systems like [WebIDL](https://webidl.spec.whatwg.org/#idl-types) and select a subset that makes sense in our context.

**Comment by relu91** [comment]
@zolkis may I ask to have feedback on this idea?

**Comment by zolkis** [comment]
> A Data Schema Value is anything that is valid for any of the defined DataSchemas 

This is too vague, it's better formulated like a note that the algorithms handling DataSchemas define the user agent behavior, or something like that.

**Comment by relu91** [comment]
> This is too vague, it's better formulated like a note that the algorithms handling DataSchemas define the user agent behavior, or something like that

I agree that is too vague, but we need a data model that we can refer to in Payload format Binding. Like :
> Convert this payload format to a WoT number (with WoT number I'm referring to a value that is valid for NumberDataSchema) by bla bla 

[WebIDL](https://webidl.spec.whatwg.org/#idl-types) might work, but I'm not sure it is ok to add this dependency inside the protocols binding templates documents or in TD spec...

**Comment by egekorkan** [comment]
I actually find the above definition quite alright. It is indeed too vague but a good start. Validity is maybe something that is not always specific enough. Still being maybe vague, if I were to write it, I would say :

> Data Schema describes how a payload SHOULD look like. A serialization of the Data Schema (such as JSON Schema, XML Schema, SHACL, etc.) can be used for validation of a payload with the corresponding media type (such as JSON, XML, RDF respectively). This validation is commonly done with tools that take a schema instance and run validation algorithms against given payloads as input. Validation is not the only use case for data schemas, other examples include UI generation, auto-completion of payloads and code, code generation.

A nice discussion though ;)

**Comment by zolkis** [comment]
It's a circular definition. An algorithmic approach, or pointing to existing algorithms/standards would be much better.

**Comment by egekorkan** [comment]
For validation or the definition of individual schema formats, there are multiple like JSON Schema, XML Schema, SHACL etc. However, the binding to them is something we are inventing

**Comment by zolkis** [comment]
We need to explicitly list the supported schema formats with their algorithms. Standardization needs exact descriptions.
Otherwise we could say "this program/value is valid in whatever environment that considers it valid".

**Comment by egekorkan** [comment]
From the call of 15.12.21:
This looks like a promising approach. It would be good to add this in the TD spec after the paragraph in section 5.2 that says:

> Though this definition does not prevent Objects to include multiple name-value pairs with the same name, they are generally not considered in this specification. An Object whose elements only have numbers as names is called an Array. Similarly, an Object whose elements only have Terms (that do not belong to any Vocabulary) as names is called a Map. All names appearing in some name-value pair in a Map are assumed to be unique within the scope of the Map. 

We still need to decide whether this should be normative or informative.

**Comment by relu91** [comment]
After a closer read of the Thing Description specification, I found out that the [Preliminary definitions](https://w3c.github.io/wot-thing-description/#preliminary-definitions) section has already good definitions for `Object`, `Array` etc. My misunderstanding was because the [Object schema](https://w3c.github.io/wot-thing-description/#objectschema) section does not correctly refer to the `Object` definition described in [Preliminary definitions](https://w3c.github.io/wot-thing-description/#preliminary-definitions). I'll open a PR to fix this and I might also open an issue to discuss the possibility to use WebIDL as the source of the definition of those terms. Other than this I think that the issue is solved. 

Feel free to re-open it if anything.
