### ISSUE TITLE
Linking to Binding Documents from the Readme

### ISSUE THREAD

**Issue by JKRhb** [w3c/wot-binding-templates#146]
After the restructuring into multiple documents, accessing the the Editor's Drafts for individual protocol bindings has become a bit less comfortable as you first need to open the main document and then navigate to the table with the bindings overview to access protocol specific drafts (in contrast to accessing them directly via the table of contents).

I think it could make sense to also add these links to the README file to be able to access them more quickly and to also give an overview in the repository regarding which bindings are currently being worked on.

**Comment by egekorkan** [comment]
I can add them to the readme. About the following:
> give an overview in the repository regarding which bindings are currently being worked on.

Do you mean the ones who are not released yet and will be released soon (and are active)?
