### ISSUE TITLE
How does a Protocol Binding represent an item which is created as a result of an interaction

### ISSUE THREAD

**Issue by mjkoster** [w3c/wot-binding-templates#15]
Several use cases involve invocation of an action or subscription to an event where an item is created as a result of the interaction.

**Comment by vcharpenay** [comment]
Here is an example of a REST API to send commands to a building automation system:

1. `POST /commands { input parameters }`
    1. `{ "id": "someId", "createdAt": "2017-12-12T14:57:23", "currentStatus": 5 }`
2. `GET /commands/someId` (or observe)
    1. `{ "currentStatus": 10 }`
    2. `{ "currentStatus": 15 }`
    3. ...
    4. `{ "currentStatus": 100 }`

`currentStatus` gives the progress in percent.

**Comment by egekorkan** [comment]
This is being tracked in #41

**Comment by takuki** [comment]
On September 20 in Fukuoka, it was suggested to allow to define this at the top level, or simply make it implicit. See minutes [here](https://www.w3.org/2019/09/18-wot-minutes.html#item13).

**Comment by egekorkan** [comment]
I think this should be also protocol unspecific and be handled by the Thing Description specification as somewhat indicated in the new [charter](https://cdn.statically.io/gh/w3c/wot/master/charters/wot-wg-charter-draft-2019.html?env=dev#complex-interaction). I would propose to close this issue if no objection by 25.01.2020

**Comment by egekorkan** [comment]
The discussion should continue in the TD specification at https://github.com/w3c/wot-thing-description/issues/302
