### ISSUE TITLE
CoAP `Content-Format` vs. `contentType`/`contentCoding`

### ISSUE THREAD

**Issue by JKRhb** [w3c/wot-binding-templates#159]
In the context of the new CoAP Binding Template, there were a couple of discussion (see e.g. https://github.com/w3c/wot-binding-templates/pull/149#discussion_r813994731) regarding the relationship between CoAP's `Content-Format`s which are numeric codes representing a combination of the `contentType` and `contentCoding` in TD forms.

While it is no problem mapping a `Content-Format` to a `contentType` and `contentCoding` (see the [corresponding table](https://www.iana.org/assignments/core-parameters/core-parameters.xhtml#content-formats) in the IANA registry), the other direction is not as straightforward as there are gaps in the set of Content-Types and encodings that are supported by CoAP (each new Content-Format has to be explicitly registered with IANA).

@ektrah's proposed solution in the current version of the CoAP Binding Template is to add a new vocabulary term called `coap:format`, where you can include numeric values for Content-Formats like so (also see #149 and #158):

```json
{
    "op": [ "writeproperty" ],
    "href": "coap://[2001:DB8::1]/.../...",
    "coap:method": "PUT",
    "coap:format": 112  // application/senml+cbor
}
```

This solves the problem that Consumers would need to always have a copy of the IANA registry otherwise.

However, there is the problem that forms have a default `contentType` of `application/json`, so in order to indicate a different Content-Format you would need to also override that field (c. f. https://github.com/w3c/wot-binding-templates/pull/158#discussion_r858922459):

```json
{
    "op": [ "writeproperty" ],
    "href": "coap://[2001:DB8::1]/.../...",
    "coap:method": "PUT",
    "coap:format": 112,
    "contentType": "application/senml+cbor"
}
```

For me, this raises a couple of questions/possible solutions for this problem in CoAP forms:

1. Should TDs be required to always indicate the `contentType` next to the `Content-Format` like in the second example? This has the disadvantage of creating redundancy, but would ensure maximum compatibility.
2. Show only "allow" `contentType` and `contentCoding` combinations be allowed that are mappable to CoAP Content-Formats? This would allow omitting/dropping the extra `coap:format` field, but Consumers would still need to have the IANA registry at hand.
3. (Should `contentType` and `contentCoding` be declared as HTTP-specific in TD 2.0? This could also address problems with other protocol binding templates.)

The last point is not suited for the current TD version, but should probably be kept in mind for the next one.

Looking forward to your thoughts and ideas on this issue!

**Comment by egekorkan** [comment]
I think the short term solution is to require both and with an additional schema validation (like in Modbus binding). 
Making `contentType` required or not based on the protocol would be an option. That would mean that also for HTTP we would need a second schema validation (might be a good thing actually).

**Comment by egekorkan** [comment]
I had a talk with @ektrah and the decision is to say that we do not need the number-based representation anymore. The consumer needs to have encoder/decoder for the contentTypes anyways and thus it should be able to map the string based representation (`application/senml+cbor`) to the number based representation via coap ontology (`112`)

**Comment by JKRhb** [comment]
> I had a talk with @ektrah and the decision is to say that we do not need the number-based representation anymore. The consumer needs to have encoder/decoder for the contentTypes anyways and thus it should be able to map the string based representation (`application/senml+cbor`) to the number based representation via coap ontology (`112`)

Sounds good :) Maybe the Binding document should state then that only Content-Formats that are registered with IANA should be used in forms using a CoAP URI scheme?

**Comment by egekorkan** [comment]
> > I had a talk with @ektrah and the decision is to say that we do not need the number-based representation anymore. The consumer needs to have encoder/decoder for the contentTypes anyways and thus it should be able to map the string based representation (`application/senml+cbor`) to the number based representation via coap ontology (`112`)
> 
> 
> 
> Sounds good :) However, maybe the Binding document should state then that only contentTypes that are mappable to Content-Formats registered with IANA should be used in forms using a CoAP URI scheme?

I think so yes. I think that the number-based representation with not registered formats would be very annoying and not interoperable

**Comment by ektrah** [comment]
#158 removes the CoAP-specific form members with numeric IDs (`cov:format` and `cov:accept`) but doesn't fully describe yet how to use the string-based members (`contentType` and `contentCoding`).

I think, ultimately, the implementation of a consumer using CoAP will need to have code that looks roughly like this:

```ts
// request payload
if (condition1) {
    determine the request payload format;
    include a payload using that format in the request;
    include a Content-Format option with the ID of that format in the request;
}

// content negotiation
if (condition2) {
    determine the response payload format;
    include an Accept option with the ID of that format in the request;
}
```

For example, with `cov:format` and `cov:accept`, it would look like this:

```ts
let request = new Request();

// request payload
let acceptedFormats = form["cov:format"];
if (acceptedFormats is number) {
    acceptedFormats = [ acceptedFormats ]; // wrap single value in array
}
if (acceptedFormats is array) {
     let payloadFormat = SelectBestFormat(acceptedFormats);
     request.SetPayload(CreatePayload(payloadFormat));
     request.SetContentFormatOption(payloadFormat);
}

// content negotiation
let availableFormats = form["cov:accept"];
if (availableFormats is number) {
    availableFormats = [ availableFormats ]; // wrap single value in array
}
if (availableFormats is array) {
    let acceptedFormat = SelectBestFormat(availableFormats);
    request.SetAcceptOption(acceptedFormat);
}
```

It's quite unclear to me what `condition1` and `condition2` should be based on the explanation in https://github.com/w3c/wot-thing-description/issues/1531.

**Comment by JKRhb** [comment]
I think TD examples for `condition1`and `condition2` could look like the following:

```json
"properties": {
  "exampleStatus": {
    "forms": [
      {
        "op": "writeproperty",
        "href": "coap://example.org",
        "cov:method": "GET",
        "contentType": "application/json" // => Content-Format option with value 50
      },
      {
        "op": "readproperty",
        "href": "coap://example.org",
        "cov:method": "PUT",
        "contentType": "application/cbor" // => Accept option with value 60
      },
    ]
  }
},
"actions": {
  "toggle": {
    "exampleAction": {
      "forms": [
        {
        "href": "coap://example.org",
        "contentType": "application/cbor", // => Content-Format option with 60
        "response": {
            "contentType": "application/cbor", // => Accept option with 60
          }
        }
      ]
    }
  }
}
```

So by default, a form's `contentType` would imply both a value for the Content-Format and Accept option, while the latter can be overridden using a `response` member. Is that also what you had in mind, @egekorkan?

**Comment by egekorkan** [comment]
@JKRhb this is exactly what I had in mind. I have also put a PR at the TD (https://github.com/w3c/wot-thing-description/pull/1564) that puts these in a table.

**Comment by ektrah** [comment]
It's still unclear to me what `condition1` and `condition2` are. Could you describe it in (pseudo-)code?

**Comment by JKRhb** [comment]
I suppose the simplest scenario could look something like this:

```typescript
function applyContentFormatsToRequest(form: CoapForm, request: CoapRequest) {
    const contentFormat = form.contentType; // Note: Content-Coding needs to be respected here as well
    if (contentFormat != null) {
        request.setOption("Content-Format", contentFormat);
    }

    // Try to use the contentType of the form's response member, use form's contentType as fallback
    const accept = form.response?.contentType ?? form.contentType;
    if (accept != null) {
        request.setOption("Accept", accept);
    }
}
```

This does not factor in a number of the cases listed by @egekorkan in https://github.com/w3c/wot-thing-description/pull/1564, but I guess it can be a starting point.

By the way, I started updating node-wot's CoAP implementation to the latest binding version in https://github.com/eclipse/thingweb.node-wot/pull/768, feel free to comment there as well :)

**Comment by egekorkan** [comment]
Discussion in the call of 19.10.2022:
- First of all, there is a high level problem about how to interpret the `contentType` in the TD spec. Ege's PR at https://github.com/w3c/wot-thing-description/pull/1564 tries to address this but fails to capture what should happen in the protocols.
- There are protocols with no header information or protocols like HTTP that can say that the client accepts one content type (accept header) and can also say the content type of the payload. The contentType of the form should be used for constructing the messages and can be used to validate the contentType of the response.
- How to build payloads and headers should be explained. A protocol-agnostic way can be done in the TD and each protocol can further explain this
- Extending the table of the pr in the td spec (https://github.com/w3c/wot-thing-description/pull/1564) should be improved. A proposal is to split this into a simple case of having only one contentType (no response or additionalResponses) and then work on a more complex one. Even the simple case is not so simple given the request and response.
- The group definitely does not want to have contenttype in affordance level.
- There seems to be a bug in the node-wot implementation (current master, not PRs) where sometimes the header of the response is used for decoding and sometimes the contentType in the TD. It is a bug but then it is not clear in the TD spec what should be done with this keyword.

**Comment by egekorkan** [comment]
@ektrah @JKRhb @mkovatsc @relu91 feel free to even edit my comment above, I hope I could conveyed the opinions

**Comment by ektrah** [comment]
@JKRhb @egekorkan Now that #193 is merged, can this be closed?

**Comment by JKRhb** [comment]
Yes, I think this should be resolved :)
