### ISSUE TITLE
MQTT binding examples

### ISSUE THREAD

**Issue by a-hennig** [w3c/wot-binding-templates#167]
small changes
- example 7 has some small json errors (comma before `}` ) 
-  also it would be good to use different topics for read/observe and write in the example, since this is very often done in mqtt applications / topics layouts

the text and examples do not touch on the content problem of mqtt .. that everybody is crafting their own message payload.
the examples seem to assume a "every property their own subtopic, content as json", which is only one of several ones I've seen.  E.g. also the ""every property their own subtopic, content as string (i.e. no quotes and json escapes)" and "every thing their own subtopic, content as json".

I understand, if this would at current time overload the mqtt binding (I'd rather have a version released now and extend later), but it would help if this is made explicit as "out-of-scope" or "out-of-scope for now".

**Comment by egekorkan** [comment]
I think that "payload as a protocol" topic is something we have to cover in WoT in general. There is an issue here https://github.com/w3c/wot-binding-templates/issues/125

This happens in HTTP, WS, and now that I learn it, in MQTT as well (sadly). It would be nice topic for the new charter
