### ISSUE TITLE
[Modbus] URI design for modbus+tcp URI schemes

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-binding-templates#176]
I had a look at the Modbus binding and noticed that addressing information is split among URI and additional TD terms (e.g., `modbus:address`, `modbus:quantity`).

The URI should also for Modbus hold all the addressing information necessary to identify and locate the "Modbus resource" (i.e., registers, coils).

To illustrate: currently it is as if you would only put the "http://device.example.com:8080" part into the URI/href field, and define custom terms to hold "/api/properties/prop1"...

**Comment by egekorkan** [comment]
Actually we have this problem for MQTT as well since the `href` alone cannot identify a resource due to rules on `/` . Even though that `href` should identify a resource, we will not be able to do this in all protocols. Websocket driven protocols would be another example of such patterns

**Comment by mkovatsc** [comment]
One part here is that it is not fully understood how URI schemes work: they fully define how the rest of the URI has to be parsed; it does not have to be the same way as HTTP URIs work. An example here are `urn:` URIs. While `modbus-*` URIs should work somewhot similar to HTTP URIs, they must be able to fully address a Modbus resource.

I am not deep enough anymore, so cannot follow what the MQTT issue is. Nonetheless, MQTT does not have a URI scheme yet and we can fix the issue.

WebSockets, however, do have a URI scheme already registered with IANA. Furthermore, it is usually hard to convince the "Big Web" community of IoT use cases so that the spec would be updated...

**Comment by mkovatsc** [comment]
Overall, we have a strong use case for the Modbus binding and would like to help to move it forward. Are there still dedicated Binding calls or can we organize something like a mini-workshop call?

**Comment by egekorkan** [comment]
I see the point, we can simply omit the `/` driven syntax. You are more than welcome to join the calls! The Binding Templates Discussions take place during the TD calls. We have a pause due to TPAC but in two weeks, they will be back (https://www.w3.org/WoT/activities/meetings/).

**Comment by relu91** [comment]
> One part here is that it is not fully understood how URI schemes work: they fully define how the rest of the URI has to be parsed; it does not have to be the same way as HTTP URIs work. An example here are urn: URIs. While modbus-* URIs should work somewhot similar to HTTP URIs, they must be able to fully address a Modbus resource.

I like the idea, but the only small problem that I'm seeing is that in the documents we are talking about URLs and not URIs. However, TD `forms` `href` accept `anyURI` therefore changing to URIs should not be a big deal. Another implication that I am seeing is about the `base`. I am sure if there is a notion of a base outside of HTTP URIs... 

Anyhow PR incoming with some concrete proposal.

**Comment by mkovatsc** [comment]
> I like the idea, but the only small problem that I'm seeing is that in the documents we are talking about URLs and not URIs. 

Not sure what you mean: https://www.rfc-editor.org/rfc/rfc3986#section-1.1.3
