### ISSUE TITLE
Review Comments: W3C Editor's Draft 23 January 2018

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-binding-templates#21]
The review comments below apply to the W3C Editor's Draft 23 January 2018 at:
https://rawgit.com/mjkoster/wot-binding-templates/initial-spec-contribution/index.html

### Examples in chapter 2
The examples are very useful to understand the concepts.
However the spec needs to give explicit references to OCF, IPSO, SenML, LWM2M 
e.g.:
[SenML] - https://tools.ietf.org/html/draft-ietf-core-senml-12

#### OCF
- Which version of the OCF specification is used? 1.0 or 1.3? 
- Attribute names in the example need fixing:
- ##### Example:
> [
> 	{
>  		"href" : "/example/light/level",
> 		"rep" : {
> 			"**dimmingSetting**": 50
> 		}
> 	} , {
>  		"href" : "/example/light/time",
> 		"rep" : {
> 			"**rampTime**": 10
> 		}
> 	} 
> ]

These name changes need to be carried through to the examples further down.

### Chapter 2.2.3

It should be described how additional protocols can be integrated, so a guideline for binding to other protocols would be useful. 

#### HTTP binding
If we consider HTTP, do all protocol implementations support the same set of header options? Is there a way for a thing to set protocol headers?

### Chapter 3
This chapter informatively describes abstract methods (invokeAction, cancelAction, modifyAction, readProperty, writeProperty, subscribeEvent, unsubscribeEvent, observe) on the classes from the Vocabulary Definition in chapter 5 of the TD spec. Chapter 5 does not contain these methods. They need to be normatively specified in the TD.

What is "modifyAction" doing?

What is the purpose of "observe"?

### Chapter 4

what is meant with the term "value scaling"?

### Chapter 5

"observe" is currently specified for all elements of the TD. Is that intentional?

**Comment by egekorkan** [comment]
@mlagally will look to see which problems are still relevant

**Comment by egekorkan** [comment]
> Attribute names in the example need fixing:
Done

> It should be described how additional protocols can be integrated, so a guideline for binding to other protocols would be useful.

A paragraph on this added just before 5.3.1

> If we consider HTTP, do all protocol implementations support the same set of header options? Is there a way for a thing to set protocol headers?

This should be specified in the forms. If a Thing requires the client to set the Accept header and the client is not able to do so, it is the client's problem.

> This chapter informatively describes abstract methods (invokeAction, cancelAction, modifyAction, readProperty, writeProperty, subscribeEvent, unsubscribeEvent, observe) on the classes from the Vocabulary Definition in chapter 5 of the TD spec. Chapter 5 does not contain these methods. They need to be normatively specified in the TD.

This is done in the TD spec very well.

> What is "modifyAction" doing?

Removed until further notice. This was already the case in the last WG note.

> What is the purpose of "observe"?

I think this is also well defined in TD and Architecture specs.

> what is meant with the term "value scaling"?

I have remove the whole _Processing Model and Runtime_ section since the content is really not clear. @mjkoster could you explain what is trying to be explained [here](https://w3c.github.io/wot-binding-templates/#processing-model)

> "observe" is currently specified for all elements of the TD. Is that intentional?

I think that this is not relevant anymore?

> Which version of the OCF specification is used? 1.0 or 1.3?

Added version 1.3

> However the spec needs to give explicit references to OCF, IPSO, SenML, LWM2M

Added references

Changes are tracked in #95

**Comment by egekorkan** [comment]
All issues are handled in #95.
