### ISSUE TITLE
RDF-compliant inputData/outputData modeling

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-binding-templates#23]
> Comments from PR #20 by @vcharpenay:

I see two changes here: first, the `@type` statement is split into type parts and, second, you merge `DataField` and `DataSchema` classes.

Let me address them separately on this example:
```js
"fields": [
    {
        "name": "level",
        "@type": ["sch:levelvalue"],
        "type": "integer",
        "min": 0,
        "max": 255
    },
```

_Note: what about relying on the deployed iotschema.org vocabulary for your examples? Here, `sch:levelvalue` corresponds to http://iotschema.org/CurrentLevel. There is a typo in the class definition (hence, the 404 page) but the class exists._

#### Type statement

`@type` is a JSON-LD reserved keyword that maps to [rdf:type](http://www.w3.org/1999/02/22-rdf-syntax-ns#). I assume that in the statement `_:subject rdf:type sch:levelvalue`, I assume that the statement subject (`_:subject`) is something like "203 with timestamp 2018-01-19T09:46:16+00:00", i.e. an actual level value.

The example schema definition above would map to RDF statements like:
```
_:subject
    rdf:type sch_levelvalue ;
    td:type td:Integer ;
    xsd:minInclusive "0" ;
    xsd:maxInclusive "255" .
```

in which, `_:subject` is the schema definition that validates "203 with timestamp 2018-01-19T09:46:16+00:00" and not the value itself. In fact, it would be more consistent if `@type` was `integer`, as defined [here](https://github.com/w3c/wot-thing-description/tree/master/ontology/td-types). For the same reason, `"@type": ["integer", "sch:levelvalue"]` would be an incorrect definition.

#### DataField vs. DataSchema

I am not sure that the change you propose here is consistent with the [JSON schema validation spec](http://json-schema.org/latest/json-schema-validation.html), where fields must have a name and a value, which in turn must be a valid JSON schema. The spec is hard to interpret, though. But anyway, to me, this change also limits the reuse of schema definitions. For instance, one could give a unique URI to the definition of a byte value:
```js
{
    "@id": "http://example.org/Byte",
    "name": "byte value",
    "@type": "Integer",
    "minimum": 0,
    "maximum": 255
}
```

You would then simply declare the following in your TD, as defined the current spec:
```js
"fields": [
    {
        "name": "level",
        "value": "http://example.org/Byte"
    },
```

If you merge `DataField` and `DataSchema`, you cannot simply reference this new  `Byte` type.

**Comment by mkovatsc** [comment]
It is hard to derive the correct syntax from your comments. Need to come up with such a proposal for the FPWD.

**Comment by vcharpenay** [comment]
Here is my proposal for the example mentioned above:
```js
"fields": [
    {
        "name": "level",
        "value": {
            "@type": "Integer",
            "reference": ["iot:CurrentLevel"],
            "minimum": 0,
            "maximum": 255
        }
    },
```

Changes:
- `sch:levelvalue` replaced by `iot:CurrentLevel` to adopt existing iotschema.org terms (minor change)
- `name`/`value` kept sperate for the sake of reusability (and consistency [with JSON Schema - Sect. 6.5.4](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.5.4))
- `reference` used to reference RDF classes to avoid using "type" several times
  - note: this term is still not well-defined, `reference` is more of a placeholder
- `@type` used for the value type (i.e. number, integer, boolean, string, object or array)
- `Integer` written with capital letter to emphasize it is an RDF class
- `min` replaced by `minimum`, see [JSON Schema - Sect. 6.2.4](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.2.4) (minor change)
- `max` replaced by `maximum` see [JSON Schema - Sect. 6.2.2](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.2.2) (minor change)

**Comment by mkovatsc** [comment]
I think we need a good graphical representation of the model here to not get confused by JSON syntax -- similar to what we needed for a proper TD discussion.

* http://iotschema.org/CurrentLevel is also 404 -- I think the whole site broken at the moment
* name/value: I expected a similar transformation as for the JSON-LD 1.1 proposal, where object keys (cf. Mozilla TD) are transformed to `name` properties within the JSON-LD 1.0 array structure used (cf. WoT TD). I could not find the proper Issue where this was discussed -- what is the actual status here?
* @type vs reference: I am very confused why `Integer` and `iot:CurrentLevel` are not related classes, similar to TD Interaction annotations. It should work similar to the Interaction @type, for instance, being `Property` and more specific classes are added to the same @type array. (This is connected to another discussion that it would be helpful to separate the main information (Integer/Property) from additional semantic annotations (iot:CurrentLevel/[Temperature](https://w3c.github.io/wot-thing-description/#temperature-sensor) ).

**Comment by mkovatsc** [comment]
One of the main assumptions above is that semantic annotations should work the same at the Interaction level and the Data level.

**Comment by mkovatsc** [comment]
In the call on 30 Jan 2018 we confirmed:

* TDs should still contain all syntactic information when LD markup (@...) is ignored. This means, `Integer` etc. (basic syntactic info) need to go into a TD-defined term that is not ignored.
* iotschema.org definitions work at specific levels: Thing, Capabilities, Interactions, Data. `iot:CurrentLevel` would be compatible with `Integer`, and hence also can have the relation `rdf:type` ergo be an `@type` value.
* References such as `http://example.org/Byte` should go into `@type`, no?

Personally, I still cannot see how @vcharpenay 's proposal is able to define recursive structures. At the top level, `type` can take `object` and then has the `fields` array. Each entry therein must be able to be of `type`: `object` again. This breaks if suddenly `@type` is used.

**Comment by mjkoster** [comment]
We seem to have rough consensus on most of this since the web teleconference of January 31.

We will use @type for RDF type; what did we decide for the JSON Schema type, is it "type" or "datatype".

It seems like having both "@type" and "type" in the same document is a bit confusing, but JSON schema already defines "type" and LSON-LD already defines @type.

What should we decide?

**Comment by mkovatsc** [comment]
+1 to rename to `dataType`.

We already diverge from the vocabulary (`property` --> `field`) and we use `mediaType` instead of the the link target attribute `type` to be more precise.

**Comment by zolkis** [comment]
+1 for `dataType`, and also +1 for using `property` instead of `field`, and also +1 for `mediaType` in links.

**Comment by mkovatsc** [comment]
Given that we want to go toward the JSON-TD proposal after Prague, the term `property` would become `properties` and will conflict with the top-level `properties` Interactions. Thus, we changed from `property` to `field`.

When going for `properties` and inheriting the semantics, one can think down the line to have recursive Properties, that is, Properties can have sub-Properties, which in some cases might be directly addressable. This is quite nice and would match @draggett 's proposal; I also see a use case for LWM2M/IPSO objects.

The issue is that a data schema containing `properties` becomes useless for Actions and Events. Arguments sent to Actions, Action Responses, and Event data are not directly related to Properties (a Property being an addressable and accessible exposed state of the Thing).

**Comment by draggett** [comment]
> The issue is that a data schema containing properties becomes useless for Actions and Events. Arguments sent to Actions, Action Responses, and Event data are not directly related to Properties (a Property being an addressable and accessible exposed state of the Thing).

Note that in my proposal "properties" is used within the data model for nested objects, i.e. an object whose property values may themselves be objects.  I can thus use "properties" within the data models for properties, events, action requests and responses.

**Comment by mkovatsc** [comment]
> Note that in my proposal "properties" is used within the data model for nested objects

Yes, I remember that you have that in your proposal.

How exactly do you then model Actions and Events that take or produce nested objects? What is the URI of a property that is part of an Action invocation or a sub-sub-property of emitted Event data?

**Comment by draggett** [comment]
I am not sure you are asking the right question. In my proposed algorithm for translating JSON to RDF, the properties, actions and events are translated using blank nodes. This works fine for arbitrarily nested objects for properties, events, action requests and response.

When it comes to protocol bindings to say WebSockets, the sequence of names from the thing form a path that can be readily mapped to a name[/name]* sequence.

Can you explain why you are asking about the URI of sub-properties etc.?

**Comment by mkovatsc** [comment]
The terms in the TD identify the RDF classes they are mapped to. The Property interaction nodes are mapped to a class that also describes how to access (read/write) Properties, which is done through `href` or something similar. So these Properties are semantically something that can be identified, located, and accessed. This is good because that is what we want from the Property Interaction Pattern, expose state to be directly accessed.

When you now reuse the term for Properties in the data definitions for Actions and Events, the nodes are of the same RDF class, which means they are supposed to be identified, located, and accessed. Yet these properties in payloads that are send to an Action of a Thing or in payloads sending the Event data to subscribers are not generally locatable and accessible. There is a semantic mismatch, ergo Properties (as Interactions) and accessible sub-Properties of complex/nested Properties are different from "properties" that are part of complex/nested payloads exchanged by Actions and Events.

In other terms: the data of Property Interactions can be accessed by any client that has the TD of the corresponding Thing. Data items within the "inputData"/request and "outputData"/response of an Action cannot be accessed by any client, as these are not Properties in the Interaction sense.

**Comment by egekorkan** [comment]
I think that this issue is as relevant as it is used to be? From my point of view it can be closed. What do you think @mkovatsc ?

**Comment by egekorkan** [comment]
Provided that this is now described properly, I am closing it.
