### ISSUE TITLE
Clarifying Binding Mechanism

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-binding-templates#238]
From TD and Architecture, we should bring (copyover) the parts that are about the binding mechanism

**Comment by egekorkan** [comment]
Actually, the scripting API explains how a binding should be used in software. We should use the information there.

https://w3c.github.io/wot-scripting-api/#the-readproperty-method

**Comment by egekorkan** [comment]
From the call of 15.02, some important notes: 
- We should state that a protocol binding cannot be used on its own since serialization is a MUST by the TD spec (requiring `contentType`). 
- Explain what happens when an ecosystem binding is needed and why it is needed.

**Comment by relu91** [comment]
Linking Scripting issue here: https://github.com/w3c/wot-scripting-api/issues/430

**Comment by egekorkan** [comment]
Regarding relationship to scripting: I think that a generic mechanism needs to be explained here. Not all implementations have the separation of a runtime (servient and its bindings) and the developer code. So scripting will need a more clear definition of where this separation happens than the bindings template. I think Scripting is already doing this well in the algorithms for methods like `readproperty()`

**Comment by egekorkan** [comment]
Relevant parts from TD:
- Overall meaning: https://w3c.github.io/wot-thing-description/#form the paragraph at the intro
- https://w3c.github.io/wot-thing-description/#sec-op-data-schema-mapping for overall understanding of data schema and operation relationship
- HTTP Binding: https://w3c.github.io/wot-thing-description/#http-binding-assertions
- Examples for CoAP and MQTT: https://w3c.github.io/wot-thing-description/#myLampThing-example-serialization

Relevant parts from Architecture:
- Hypermedia principle: https://w3c.github.io/wot-architecture/#sec-affordances
- Protocol Bindings section: https://w3c.github.io/wot-architecture/#sec-protocol-bindings
- Media Types section: https://w3c.github.io/wot-architecture/#media-types
- Binding Templates building block: https://w3c.github.io/wot-architecture/#sec-binding-templates -> This has a nice diagram that should be considered.
- TDs for existing devices: https://w3c.github.io/wot-architecture/#existing-impl

If I have forgot about something, I will update the lists above based on the comments.
