### ISSUE TITLE
Rename cov:block2SZX to cov:block2Size

### ISSUE THREAD

**Issue by ektrah** [w3c/wot-binding-templates#256]
We should rename `cov:block2SZX` and `cov:block1SZX` to `cov:block2Size` and `cov:block1SZX`, respectively, as the SZX field actually contains the encoding of the size (0, 1, 2, ...) and not the size itself (16, 32, 64, ...).

**Comment by ektrah** [comment]
You're fast! 😃

Thanks!

**Comment by ektrah** [comment]
Or maybe `blockSize2` and `blockSize1`?

**Comment by JKRhb** [comment]
> Or maybe `blockSize2` and `blockSize1`? 

I think I would tend to keep it as `block2Size`/`block1Size` (to make the Block2/Block1 association a bit more explicit), but I don't feel strongly about it. If you prefer `blockSize2`/`blockSize1`, we can also use that :)

**Comment by egekorkan** [comment]
> Or maybe `blockSize2` and `blockSize1`?

@ektrah we are going to merge #259 since you have approved it. If you prefer the other notation, we can reopen this issue
