### ISSUE TITLE
[note3] Pubrules errors

### ISSUE THREAD

**Issue by ashimura** [w3c/wot-binding-templates#294]
When I checked the [draft for publication](https://w3c.github.io/wot-binding-templates/publication/note3/Overview.html) using the [Pubrules checker](https://www.w3.org/pubrules/?url=https%3A%2F%2Fw3c.github.io%2Fwot-binding-templates%2Fpublication%2Fnote3%2FOverview.html&profile=NOTE&validation=simple-validation&informativeOnly=true&echidnaReady=false&patentPolicy=pp2020), there were the following two errors:
* The link for "Note track" in publisher paragraph in the Status of This Document is not correct. The right link is: <a href="https://www.w3.org/2023/Process-20230612/#recs-and-notes">Note track</a>
* The link for text 'permissive document license' is expected to be 'https://www.w3.org/Consortium/Legal/copyright-software' or 'https://www.w3.org/Consortium/Legal/2023/software-license', but found 'https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document' in document.

**Comment by egekorkan** [comment]
Issue fixed and published
