### ISSUE TITLE
Modbus spec and schema does not match on terms

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-binding-templates#295]
https://w3c.github.io/wot-binding-templates/bindings/protocols/modbus/index.html#form-terms has function but the schema has functionCode at https://github.com/w3c/wot-binding-templates/blob/main/bindings/protocols/modbus/modbus.schema.json#L22

**Comment by relu91** [comment]
Actually, there are other errors, the JSON schema is not updated with the latest changes. Let me fix them.
