### ISSUE TITLE
"Philips Hue with HTTP" in Figure 1 of the note of the WoT Binding Templates

### ISSUE THREAD

**Issue by chachamimm** [w3c/wot-binding-templates#300]
There is the description of "Philips Hue with HTTP" in[ Figure 1](https://www.w3.org/TR/2023/NOTE-wot-binding-templates-20230928/#fig-building-block) of the note of the WoT Binding Templates. "Philips Hue" is the products of Philips. So I don't think its is appropriate to use "Philips Hue".

Thank you,

**Comment by egekorkan** [comment]
Do you mean because it is a commercial product? I do not think it is wrong to mention that WoT can be used by commercial products and that there can be bindings for them.

**Comment by egekorkan** [comment]
It is also part of the WoT Architecture at https://w3c.github.io/wot-architecture/#fig-binding-templates since these figures are shared between the two specs.

**Comment by chachamimm** [comment]
> Do you mean because it is a commercial product?

Yes.

I make sense for @egekorkan's comment. But I think this issue is the policy issue how a commercial product is handled. 

I think that we should be very careful when handling commercial products. But if there is a consensus of handling commercial products in W3C and WoT WG, I follow it.

And a issue of architecture is as same as this issue.

**Comment by egekorkan** [comment]
Call of 18.10:
- We will replace the mention of Philips Hue with "Custom HTTP devices" (or something like that) and then in a paragraph, an example of Philips Hue, Shelly and others can be given.

**Comment by k-toumura** [comment]
@egekorkan I created an SVG file by changing "Philips Hue with HTTP" to "Custom devices with HTTP" for the WoT Architecture (but whether to incorporate it into the REC is a separate decision...).  Please feel free to use it if it works for you.  If you already have created, I'd appreciate it if you could allow us to use it for the Architecture to maintain consistency.
![binding-templates](https://github.com/w3c/wot-binding-templates/assets/30313213/5dc568ea-fc69-4dda-a818-012a88739d60)

**Comment by egekorkan** [comment]
Thanks @k-toumura ! Did you use this one here: https://github.com/w3c/wot-binding-templates/blob/main/images/binding-templates.svg ? You can make a PR to change it, which should automatically change the figure in the rendered specification.
