### ISSUE TITLE
Data Mappings section has unclear purpose

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-binding-templates#310]
The section at https://w3c.github.io/wot-binding-templates/bindings/protocols/bacnet/index.html#datatype-mappings needs an introduction why this is needed.

**Comment by egekorkan** [comment]
Other comment from @relu91 : The word "mapping" is confusing. We can add something like "How to use WoT Data Schema with BACnet types"

**Comment by fennibay** [comment]
@egekorkan @relu91 I tried to address the concerns in #314, please check.

**Comment by egekorkan** [comment]
We merged #312 and #314 but we need to address the following before closing this issue:

> We should be more assertive and say that the data types in forms should fit the data schema in the affordance level.
