### ISSUE TITLE
Add the "subProtocol" form element

### ISSUE THREAD

**Issue by mjkoster** [w3c/wot-binding-templates#33]
As discussed in the 2018-02-18 main WoT call, the subProtocol term is to specify which mechanism(s) to use for getting asynchronous notifications over http.

the choices are [ "LongPoll", "EventSource", and WebSocket" ]

where WebSocket is the simple upgrade to a dedicated socket for each interaction

PR #32 has this change

**Comment by mkovatsc** [comment]
WebSockets have their `ws:` and `wss:` URI schemes.

Anyhow, `subProtocol` has been adopted in the TD spec. Closing.
