### ISSUE TITLE
[MODBUS] - Accessing bit data from Holding/Input registers

### ISSUE THREAD

**Issue by rlabbeptc** [w3c/wot-binding-templates#355]
I wanted to share a use case that the current Modbus definitions don't seem to support. In the field it's common for devices to have bit-based data packed into holding registers. These individual Boolean statuses will often be desired to have their own property or object to monitor the value without needing to do Boolean lookups from the full register value.

I don't see any method to define this in the thing description as the schema is defined today. Is this a use case that is being considered?

**Comment by egekorkan** [comment]
Hi @rlabbeptc ! Yes we have some issues tracking this. See https://github.com/w3c/wot-thing-description/issues/1930 . We will probably refer to this as data mapping in the future.

**Comment by rlabbeptc** [comment]
Thanks for pointing that out and appreciate the feedback. That looks to be exactly what I was thinking. I'll close this since this is being tracked by that issue.
