### ISSUE TITLE
Typo: readData, writeData in rel -> readProperty, writeProperty

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-binding-templates#36]
In the first full example, the switch and brightness properties use rel values of readData and writeData.  According to the text, these should be readProperty and writeProperty.  The second example DOES use these values instead.

**Comment by mkovatsc** [comment]
We now aligned with the lower case style from RFC 8288 and have
* readproperty
* writeproperty
* observeproperty
* invokeaction
* subscribeevent
* unsubscribeevent
