### ISSUE TITLE
Figure Improvement and minor bug

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-binding-templates#364]
Looking at the latest [Binding Templates  Document](https://w3c.github.io/wot-binding-templates) I stumbled over two aspects that might be fixed/improved

* [Figure 1](https://w3c.github.io/wot-binding-templates/#fig-building-block): uses white text on yellow background which is *very* hard to read. Maybe use black font for "JSON, XML, ..."
* [Figure 2](https://w3c.github.io/wot-binding-templates/#fig-mechanism): In the upper part we define the action `goTo` ... below in the actual post we use `goto` (Note: all lower-case)

**Comment by egekorkan** [comment]
Call of 15.05: The first one is a good improvement. The second point is intended since it is the resource
