### ISSUE TITLE
Is rel used as a single string or as array?

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-binding-templates#38]
The latest document uses rel as a single string (e.g., Example 9) and as an array structure (e.g., Example 17). Should be both variants possible?

**Comment by mkovatsc** [comment]
As we dropped our "possible arrays must also use an array around a single element" convention for TD, yes, both should.

**Comment by mkovatsc** [comment]
See https://github.com/w3c/wot-thing-description/issues/236

Closing here.
