### ISSUE TITLE
Syntax error in Bacnet ontology

### ISSUE THREAD

**Issue by mahdanoura** [w3c/wot-binding-templates#382]
https://github.com/w3c/wot-binding-templates/blob/07230b73ccefaf99d5bda8ede6a1c354989800be/bindings/protocols/bacnet/bacnet-model.ttl#L192

**Comment by egekorkan** [comment]
@fennibay FYI :)

**Comment by fennibay** [comment]
@mahdanoura thanks for catching!

The fix is in #383, @egekorkan please merge. Or should I just push such small fixes directly to main?

**Comment by fennibay** [comment]
#383 merged, closing.
