### ISSUE TITLE
What are priorities for the next revision, next plugfest

### ISSUE THREAD

**Issue by mjkoster** [w3c/wot-binding-templates#41]
- Created action
- Websocket based notification
- Webhook/web callback based notification
- simple TD changes...

**Comment by mjkoster** [comment]
Created action is a deferred action, a "ticket" is returned with a link in a response or location header. Oracle service returns a link to (request?). Deferred or created. 202 accepted (link in response body), 201 created, or 200 OK. TD can explain how to process the response to expose a promise or observable. 202 might return a response to the application that helps processing, and later we could define a pattern. with 201, there is an action description, an interaction model with metadata that could be part of the TD with the pointer missing or a separate document with its own mediatype "ad+json", explained in the form. Need to look at Oracle and other examples to see how the returned information is handled. Fetch and also POST with returned payload. 

Simplified TD impact. Track the simplified TD proposal in the TD issue just created:

**Comment by mjkoster** [comment]
The form element will need to have an input and output section to explain the returned mediatype

**Comment by egekorkan** [comment]
We will use this issue to track and update the document to have the contents of the first comment.

**Comment by egekorkan** [comment]
The discussion on created action is continuing in https://github.com/w3c/wot-thing-description/issues/302 
Testing related aspects would be done in https://github.com/w3c/wot-testing
Regarding target protocols and websocket, there is a new issue at #92
