### ISSUE TITLE
Compile proposal for URI Templates

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-binding-templates#44]
With the DataSchema we can currently describe payloads. Many existing APIs also take parameters in the URI (e.g., the query), which would, for instance, be part of Action arguments.

We should include a mechanism similar to DataSchema to describe URI Template parameters, when `href` contains such a URI Template.

**Comment by mjkoster** [comment]
This looks good to me. Another reason to have a dataSchema element in all cases (one of dataSchema, inputSchema, outputSchema) to keep it separate from the uriSchema element. 

So in the case of the simple TD it could be 

"properties": {
  "prop1": {
    "@type": "iot:binaryswitchproperty",
    "uriParameters": {
      "on": {"type": "boolean", "@type": "iot:binaryswitchdata"}
    }
    "form":[{
      "http:method": "GET",
      "href": "http://10.0.0.1/switch{?on}
    }]
  }
}

**Comment by mjkoster** [comment]
Of course it is understood that the string serialization of the instance is to be URI-encoded, e.g. "true", "false", "1234" as string values and % encoding where needed blabla

**Comment by mkovatsc** [comment]
Just a note: @mjkoster your example is a bit overengineered by using a schema to fill in a constant -- you could just put the constant into `href` without using templates :)

**Comment by sebastiankb** [comment]
Yes, I agree to have something for TPAC on the table. Until Friday, I try to have a first draft.

**Comment by mkovatsc** [comment]
See https://tools.ietf.org/html/rfc6570 for the URI Template syntax.

**Comment by takuki** [comment]
On October 25th during Lyon F2F meeting, it was noted that both LwM2M and SmartThings API use URI parameters to carry data in requests, and the group agreed to include this feature in TD. More discussion needs to be done to decide the actual mechanisms.

**Comment by takuki** [comment]
@sebastiankb , can you make a draft with a concrete example so that we can discuss to improve to make it into the TD spec?

**Comment by egekorkan** [comment]
This issue is continuing in issue #63 since it is done in the TD spec already. We just need to include it here.
