### ISSUE TITLE
Inputs for MQTT Binding

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-binding-templates#46]
Based on the Bundang meeting there was several decisions made (also see [slides](https://www.w3.org/WoT/IG/wiki/images/d/d2/MQTT4WoT.pdf)):

1. A MQTT client that publish data to a topic with the retain=true flag it can be defined as a Property since the broker will always response with the latest cached value that was published to this topic.
2. A MQTT client that publish data with the retain=flalse flag must use the WoT event definition.
3) A MQTT client that makes subscription to an topic to initate an internal action when a corresponding data is published to this topic. In that case this action must be defined as a WoT action.
4) Defining terms for MQTT based binding: 

- **mqtt:qos** Quality of service level as number (0=at most once, 1=at least once, 2=exactly once)

- **mqtt:retain** Retain flag as boolean. If true, the broker will store the last retained message and the corresponding QoS for that topic

- **mqtt:dup** Duplicate flag for duplicated delivery

It has to be evaluated if a MQTT command term is also required (how about MQTTv5?).

**Comment by egekorkan** [comment]
A question regarding retain=true being equal to a property read:
In this case the subscriber will get the latest cached value but it will continue getting updates, thus observe. In this case, in mqtt if there is a readproperty in an op, there **has** to be observeproperty as well. If one needs to do only readproperty, an unsubscribe should follow the subsribe for a topic with retain=true?

**Comment by sebastiankb** [comment]
>In this case, in mqtt if there is a readproperty in an op, there has to be observeproperty as well. 
Correct. I think, this can be also defined as default assumption: If there is a property and a MQTT binding, the default values are retain=true and op=[readproperty, observeproperty]

**Comment by egekorkan** [comment]
Addressed in #79
