### ISSUE TITLE
align with the vocabulary in "CoAP in RDF" ontology and IANA CoRE Parameters page

### ISSUE THREAD

**Issue by mjkoster** [w3c/wot-binding-templates#47]
Change "coap:optionCode" to "coap:optionNumber" in the binding and reference implementation

**Comment by mjkoster** [comment]
Consider changing to string e.g. "GET" instead of the number code. Check impact on implementations

**Comment by mjkoster** [comment]
Based on the definition, should methodCode be the string "0.01" instead of the number 1, etc?
```
<http://www.w3.org/ns/coap#0.01> rdf:type owl:NamedIndividual ,
                                          :MethodCode ;
                                 
                                 rdfs:label "GET" 
```

**Comment by mkovatsc** [comment]
Mayve GET, POST, PUT, DELETE, FETCH, ... should go into coap:methodName?

**Comment by egekorkan** [comment]
There have been no TDs supplied to the testing inputs which include this metadata, could you provide examples?

**Comment by danielpeintner** [comment]
> Also node-wot does not include this in the forms. Any suggestions @danielpeintner ?

In node-wot it is up to the actual binding what gets put into the `form`.
See https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-coap/src/coap-server.ts#L111-L146 for CoAP.

Please create an issue or a PR if there are updates needed...
