### ISSUE TITLE
"unobserveproperty" is missing

### ISSUE THREAD

**Issue by takuki** [w3c/wot-binding-templates#54]
"unobserveproperty" needs to be added in the following sections.
1.1.1 Protocol Methods and Options
2.3.1 Bindings for Properties

In addition, section 1.1.1 also needs to include "readallproperties", "writeallproperties", "readmultipleproperties", and "writemultipleproperties".

**Comment by egekorkan** [comment]
Fixed in #71

**Comment by egekorkan** [comment]
@takuki this is now fixed in the editors draft, please review and close the issue if it is fixed

**Comment by egekorkan** [comment]
I'm closing this issue since it is fixed and available in the last editor's version
