### ISSUE TITLE
Mention of XML should be dropped

### ISSUE THREAD

**Issue by takuki** [w3c/wot-binding-templates#55]
Section 1.1.2 Media Types says that:

> Standard bridges and translations from proprietary formats to Web-friendly languages such as JSON and XML are part of the adaptation needed

Since TD natively only supports JSON at this point, I suggest we drop mention of "XML" from the sentence above.

**Comment by egekorkan** [comment]
XML is still being used and there was some work on this before. Discussion should continue

**Comment by takuki** [comment]
JSON Schema mapping to XML Schema was documented in TD spec till the [2nd Public WD](https://www.w3.org/TR/2018/WD-wot-thing-description-20180405/).

I suggest to recover the content from [here](https://www.w3.org/TR/2018/WD-wot-thing-description-20180405/#mapping-to-xml-schema) and copy into the binding templates document.

**Comment by egekorkan** [comment]
I understand that we should not drop the XML Schema translation. I would propose to do this copy-pasting into section 2.2.2 with two examples. @takuki what do you think?

**Comment by takuki** [comment]
As the content is more about DataSchema's binding to XML Schema, I think we can create a subsection under section 2.1 Data Schema. The title of the subsection can be something like "XML Schema Binding".

The entire section of _6.5.3 Mapping to XML Schema_ can be copied. 

Section 2.2.2 Content Types then make a pointer to the new subsection in section 2.1 by saying something like:

> When the content type is "application/xml" (or its binary representation "application/exi") and there is a Data Schema provided for the payload, the payloads are constrained by a XML Schema derived from the Data Schema.  See Section **2.1.x XML Schema Binding** for how to derive a XML Schema from a Data Schema definition.
> 
> Below are some examples of payloads in JSON and their corresponding equivalent payloads in XML.
>
> [Copy from Example 20, 21,22 and 23]

**Comment by egekorkan** [comment]
I have realized that the JSON Schema in the link is actually wrong. We have the following:
```
{
    "type": "object",
    "field": [
        {
            "name": "id",
            "schema": {
                "type": "integer"
            }
        },
        {
            "name": "name",
            "schema": {
                "type": "string"
            }
        }
    ],
    "required": [
        "id"
    ]
}
```
However a valid JSON Schema would be:
```
{
    "type": "object",
    "properties": {
        "id": {
                "type": "integer"
        },
        "name": {
                "type": "string"
        }
    },
    "required": [
        "id"
    ]
}
```
Does the XML Schema change in this case?

**Comment by egekorkan** [comment]
@takuki could you also specify what examples you mean by
> [Copy from Example 20, 21,22 and 23]

**Comment by egekorkan** [comment]
> I have realized that the JSON Schema in the link is actually wrong. We have the following:
> 
> ```
> {
>     "type": "object",
>     "field": [
>         {
>             "name": "id",
>             "schema": {
>                 "type": "integer"
>             }
>         },
>         {
>             "name": "name",
>             "schema": {
>                 "type": "string"
>             }
>         }
>     ],
>     "required": [
>         "id"
>     ]
> }
> ```
> 
> However a valid JSON Schema would be:
> 
> ```
> {
>     "type": "object",
>     "properties": {
>         "id": {
>                 "type": "integer"
>         },
>         "name": {
>                 "type": "string"
>         }
>     },
>     "required": [
>         "id"
>     ]
> }
> ```
> 
> Does the XML Schema change in this case?

XML Schema doesn't change

**Comment by egekorkan** [comment]
> @takuki could you also specify what examples you mean by
> 
> > [Copy from Example 20, 21,22 and 23]

https://www.w3.org/TR/2018/WD-wot-thing-description-20180405/#mapping-to-xml-schema : here are the examples

**Comment by takuki** [comment]
Section 3.1.3.1 _Object Definition to XML Schema_ starts with:

> Shown below is the type system object definition given for the inputSchema in Section Object.

It should be changed to:
> Shown below is an example type system object definition.

Section 3.1.3.2 _Array Definition to XML Schema_ starts with:

> Shown below is the type system array definition given for the input in Section Array.

It should be changed to:
> Shown below is an example type system array definition.

**Comment by egekorkan** [comment]
Fixed in commit [963843f](https://github.com/w3c/wot-binding-templates/pull/71/commits/963843f057db7d8139c4200caf6fb10effbabf02) of #71

**Comment by egekorkan** [comment]
@takuki this is now fixed in the editors draft, please review and close the issue if it is fixed

**Comment by egekorkan** [comment]
I'm closing this issue since it is fixed and available in the last editor's version
