### ISSUE TITLE
subscription, data, cancellation need to be added

### ISSUE THREAD

**Issue by takuki** [w3c/wot-binding-templates#56]
Section 2.1.1 Payload Structure, in the first paragraph mentions input and output.

We should also mention subscription, data, cancellation in the same paragraph.

**Comment by egekorkan** [comment]
Fixed in #71

**Comment by takuki** [comment]
Section 3.1.1 Payload Structure, in the first paragraph now has the following statement.

> DataSchema elements are indicated by the type, enum or const keywords in an Interaction Affordance with associated JSON Schema validation keywords. 

I am not sure if this is a correct description when we take a look at the [TD core vocabulary](https://w3c.github.io/wot-thing-description/#td-core-model) diagram.

According to the above diagram, DataSchema elements should be indicated by an instance of PropertyAffordance, input/output of ActionAffordance, data/subscription/cancellation of EventAffordance, and by uriVariable of InteractionAffordance.

**Comment by egekorkan** [comment]
I will change it as you mentioned but I would not use the word "indicated" but rather something like found.

**Comment by egekorkan** [comment]
@takuki this is now fixed in the editors draft, please review and close the issue if it is fixed

**Comment by takuki** [comment]
@egekorkan , I saw PR #71, and found it addresses this issue.
