### ISSUE TITLE
Section name 2.2.1 "Relation Types" is not accurate

### ISSUE THREAD

**Issue by takuki** [w3c/wot-binding-templates#57]
Form no longer has "rel".  What we have now is "op".

We should change the section title to something like "Operation Types".

> Form Relation Types describe the expected result of performing the operation described by the form

This sentence also should change to something like:
"Form Operation Types describe intended semantics of performing the operation described by the form."

**Comment by egekorkan** [comment]
Fixed in #67

**Comment by takuki** [comment]
Thank you @egekorkan .

Additionally, I noticed this in the same section.

> The vocabulary in section 5 lists the recommended set of form operations, and the full TD examples in section 6 contain example uses of form operations types. 

This should now be section 4 and 5, respectively.

**Comment by egekorkan** [comment]
Fixed in https://github.com/w3c/wot-binding-templates/commit/ac9e1875e40b238d814996d3ea91574f02dc58c1
Closing
