### ISSUE TITLE
Media Types should be Content Types

### ISSUE THREAD

**Issue by takuki** [w3c/wot-binding-templates#58]
Section 2.2.2 Media Types should be renamed as "Content Types".

Also, this section describes "profile" of a form, which is not defined in TD spec.
I would suggest to remove this.

**Comment by egekorkan** [comment]
Media Types fixed via https://github.com/w3c/wot-binding-templates/commit/ffbb382eb9362bb35f028db9097bb82ed43f0207

@mjkoster can you comment on "profile"

**Comment by egekorkan** [comment]
Also I would suggest moving profiles into another issue and close this one

**Comment by takuki** [comment]
I created issue #69 for the _profile_ attribute issue.

**Comment by mjkoster** [comment]
OK we can close this one then
