### ISSUE TITLE
Meta-interaction is missing from section 2.3 Interaction Types

### ISSUE THREAD

**Issue by takuki** [w3c/wot-binding-templates#59]
There needs to be a sub-section in section 2.3 discussing meta-interaction at Thing level, and how binding works at the meta-interaction level.

**Comment by egekorkan** [comment]
"readallproperties, writeallproperties, readmultipleproperties, or writemultipleproperties" are missing from protocol bindings. They need to be added

**Comment by egekorkan** [comment]
In #71 I have started adding it but not explaining how they really work.

**Comment by egekorkan** [comment]
I have added that they exist but not explaining the details. Actually I realized that I don't know how it should happen in an abstract fashion. Should the consumer _always_ try to write an array or object with multiple properties to the href indicated? If I see `property1` and `property2` (both integer types) in a TD, in a writeallproperties operation am I supposed to send `{"property1":123, "property2":33}`.

**Comment by egekorkan** [comment]
> What is the consequence of using "writeallproperties" and missing some properties?

This is also something that is not clear to me. From my point of view, unless we can send less data when doing writeallproperties (like if there was a way to omit property names since we want to write to all of them anyways), it would make sense.

**Comment by takuki** [comment]
> What is the consequence of using "writeallproperties" and missing some properties?

In my opinion, _writeallproperties_ and _writemultipleproperties_ are different in the following respect.

In _writemultipleproperties_ , only specified properties get changed.

On the other hand, in _writeallproperties_, non-specified properties get their existing values (if any) removed.

**Comment by egekorkan** [comment]
The discussion also continues on TD spec issues at https://github.com/w3c/wot-thing-description/issues/799

**Comment by egekorkan** [comment]
This discussion has resulted on adding an assertion to the TD spec. See https://github.com/w3c/wot-thing-description/pull/826

**Comment by egekorkan** [comment]
Closing since it is fixed in the latest editor's draft
