### ISSUE TITLE
subProtocol lowercase only

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-binding-templates#60]
in section 3.3.4 subProtocol should be subprotocol as defined in TD spec

**Comment by takuki** [comment]
Also, during 6/28 telecon, it was pointed out that _subprotocol_ needs more explanation in prose.

**Comment by sebastiankb** [comment]
right. Webhook would be a good candidate.

**Comment by egekorkan** [comment]
I would suggest the "more explanation" into another issue but lowercase issue is fixed via https://github.com/w3c/wot-binding-templates/commit/ffbb382eb9362bb35f028db9097bb82ed43f0207

**Comment by sebastiankb** [comment]
It says

>Currently, there is only the value "longpoll" defined for HTTP. It can be used for asynchronous event delivery or observing Properties. 

However, the[ TD spec](https://www.w3.org/TR/wot-thing-description/#form) for subprotocol mention 
>(e.g. longpoll, websub, or sse)

**Comment by egekorkan** [comment]
Fixed in #71

**Comment by egekorkan** [comment]
@sebastiankb this is now fixed in the editors draft, please review and close the issue if it is fixed

**Comment by egekorkan** [comment]
I'm closing this issue since it is fixed and available in the last editor's version
