### ISSUE TITLE
no vacabulary defintion for CoAP and MQTT yet

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-binding-templates#61]
in section section 3.3 we should clarify that CoAP and MQTT has no standardized RDF representation yet like for [http](https://www.w3.org/TR/HTTP-in-RDF10/)

**Comment by egekorkan** [comment]
it is fixed now, @sebastiankb could you review it and close it if it is OK

**Comment by takuki** [comment]
In TD spec, vocabulary terms are listed in tables with columns "Description", "Assignment" and "Type".

The columns used in section 4 Vocabulary are different.
In particular,  "Mandatory" used in this document should be changed to "Assignment" as used in TD spec.

Protocol Vocabulary are considered extension to TD vocabulary, therefore, should be described in a consistent way.

**Comment by sebastiankb** [comment]
thanks @takuki, this was also my first thought. The presentation of the tables should be similar as you can find in the TD spec. I think, the [tables ](https://www.w3.org/TR/wot-thing-description/#http-binding-assertions)are quite clear in understanding what have to be used. 


@egekorkan where does the MQTT codeNumbers (3, 8, and 10) come from?

**Comment by egekorkan** [comment]
I will rearrange the vocabularies as @takuki and @sebastiankb mentinoed.
>@egekorkan where does the MQTT codeNumbers (3, 8, and 10) come from?

They come from the MQTT specification. All the possible values are documented [here](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718021)

**Comment by sebastiankb** [comment]
>They come from the MQTT specification. All the possible values are documented here

To increase the MQTT recognition I would prefer to rely on the same term usage as you can find in the MQTT specification. That means I would prefer to use the term `controlPacketTypeValue` or short `controlPacketValue` instead `codeNumber`.

**Comment by takuki** [comment]
The table in Section **4.3.3 MQTT Vocabulary**, there is a row describing _mqv:options_ member.

The example used in _mqv:options_ is quoted below.

>  [ { "cov:optionNumber": 6, "cov:optionValue": 49 } ]

I think the above example was copied from coap section.
It should use _mqv_ prefix instead of _cov_ prefix.

**Comment by egekorkan** [comment]
@mjkoster could you comment why the term `commandCode` was chosen in the beginning and also why the integer values were used instead of the English words, i.e. why `8` instead of `SUBSCRIBE`?

**Comment by egekorkan** [comment]
I think that this issue has two different issues in it, both that don't match the title. I have created issues #72 and #73 .
Additionally, `mqv:options` is fixed in PR #71
