### ISSUE TITLE
Introduction section structure and content

### ISSUE THREAD

**Issue by takuki** [w3c/wot-binding-templates#62]
I think that Introduction section does not need to have a subsection structure.
Currently, section 1 only contains one subsection 1.1. 
I would suggest to flatten the content by removing the structure in Introduction.

Additional comments regarding the content.

> Protocol Binding Templates consist of reusable vocabulary and design pattern extensions to the WoT Thing Description format that enable an application client to interact, using a consistent interaction model, with Things that expose diverse protocols and protocol usage. 

With regards to "design pattern extension to the WoT Thing Description", can we simply say "extension to the WoT Thing Description"? Does saying "design pattern" add anything to the meaning of the sentence? Note that there is also a mention to "design pattern" in the Abstract of the document.

> As a starting point, a superset of REST and PubSub can cover most standard communication patterns. Common methods are GET, PUT, POST, DELETE, PUBLISH, and SUBSCRIBE. 

This sounds like we are defining a vocabulary for those common methods.

However, I think the plan is to define (or re-use existing) vocabularies for protocols, which means we are not defining the common methods as a vocabulary.

I think we need to re-word the above quoted sentence to reflect this.

> WoT Protocol Bindings depend on consistent use of Media Types for customization of the upper layers.

At first glance, this sentence is not very clear to me.
I suggest to describe more to make it clearer for readers of this Introduction section.

My understanding is that consistent use of Media Types is to enable properly processing serialized documents by indicating through Media Types the serialization format and additional data constraints and rules, so that the upper layer knows what to do with the data.

**Comment by egekorkan** [comment]
Fixed in #79
