### ISSUE TITLE
uriVariables needs to be described

### ISSUE THREAD

**Issue by takuki** [w3c/wot-binding-templates#63]
Section 2.2 Forms Element needs to describe _uriVariables_.

**Comment by egekorkan** [comment]
I will be putting it in Forms Element like you mentioned and I can sort of see why. `uriVariables` content appear in the `href` in a form but they are described in the Data Schema of an Interaction Affordance. In the TD spec they are under 5.3.1.2 Interaction Affordance, so @takuki why did you propose to put it under Forms Element?

**Comment by egekorkan** [comment]
Fixed in #71

**Comment by egekorkan** [comment]
uriVariables can be encapsulated in the client implementation as input parameters for an interaction execution. We are not sure how this applies to events.

**Comment by egekorkan** [comment]
@takuki this is now fixed in the editors draft, please review and close the issue if it is fixed

**Comment by egekorkan** [comment]
I'm closing this issue since it is fixed and available in the last editor's version
