### ISSUE TITLE
Inconsistency between OCF Batch Payload Example and Schema

### ISSUE THREAD

**Issue by takuki** [w3c/wot-binding-templates#64]
The constant value definitions in Example 7 DataSchema for OCF Batch Payload are:

> "const": "/light/level"
> "const": "/light/time"

To be consistent with Example 3 OCF Batch Example, they should be changed to:

"const": "/example/light/level"
"const": "/example/light/time"

**Comment by egekorkan** [comment]
Mostly a copy paste error that resulted in this typo

**Comment by egekorkan** [comment]
Fixed in #71

**Comment by egekorkan** [comment]
@takuki this is now fixed in the editors draft, please review and close the issue if it is fixed

**Comment by egekorkan** [comment]
I'm closing this issue since it is fixed and available in the last editor's version
