### ISSUE TITLE
subprotocol example and prose alignment with TD spec

### ISSUE THREAD

**Issue by takuki** [w3c/wot-binding-templates#68]
In section [**Protocol Methods and Options**](https://w3c.github.io/wot-binding-templates/#protocol-methods-options), there is an example for _subprotocol_.

> {
>   "subprotocol": "longpoll"
> }

As an example, it would be better to show an example in context (such as below excerpted from TD spec).

> {
>   "op": "subscribeevent",
>   "href": "https://mylamp.example.com/overheating",
>   "subprotocol": "longpoll"
> }

In the paragraph that precedes the example in question, there are mentions of:
> long polling, EventSource, or a simple non-multiplexed websocket protocol

To be consistent with TD spec, it should probably be changed to:
> long polling (longpoll), WebSub [websub] (websub) and Server-Sent Events [eventsource] (sse)

**Comment by egekorkan** [comment]
This is addressed in PR #67
