### ISSUE TITLE
Section 2.2.2 Media Types should clarify the usage of "profile" attribute's in TD

### ISSUE THREAD

**Issue by takuki** [w3c/wot-binding-templates#69]
Section 2.2.2 [**Media Types**](https://w3c.github.io/wot-binding-templates/#media-types) mentions _profile_ attribute.

> Additionally, there may be a profile which points to a URI for further description, for example a form with profile=http://iotschema.org/protocols/ipso.jsonld indicates that the target representation follows a set of additional encoding rules and constraints which are further defined at the URI by the profile attribute's value.

The _profile_ attribute is not defined in TD.
I would suggest to remove this from this section.

**Comment by egekorkan** [comment]
I agree, with the new profile proposals in the TD, this could be brought back once it is properly defined in the TD spec.

**Comment by mjkoster** [comment]
We need to rethink this and propose something based on a use case. For now I agree to remove "profile" from forms.

**Comment by egekorkan** [comment]
This is fixed in the latest editors draft, closing
