### ISSUE TITLE
Event Implementation Proposal (HTTP+WebSocket)

### ISSUE THREAD

**Issue by yamagile** [w3c/wot-binding-templates#7]
"HTTP + Websocket" event implementation proposal had been presented both in the Main and TD Web meetings.

The AIs generated from the Web meetings:

1. Definition about the events in TD

This AI can be divided into the following 2 parts.
  1.1. How to subscribe and unsubscribe the events? (e.g. uri, filter, handle)
  1.2. How to get the event data? (e.g. uri includes protocol information)

2. Concrete payload data

I would like to brush up my proposal by referring to the protocol binding templates ( @mjkoster ), automotive wg ( @ashimura  ), https://w3c.github.io/wot-thing-description/ , and so on.

See also https://github.com/w3c/wot-thing-description/issues/17.

**Comment by egekorkan** [comment]
@yamagile are you still interested in this?

**Comment by yamagile** [comment]
Thanks @egekorkan. I can close this issue because EventAffordance has subscription, data and cancellation as a Vocabulary term.
