### ISSUE TITLE
MQTT Vocabulary needs better terms

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-binding-templates#72]
As a continuation of #61, we need to clarify which terms the MQTT vocabulary should use. 
1. As of July 2019, `commandCode` is used whereas `controlPacketTypeValue` or short `controlPacketValue` is used in the [MQTT spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718021) as @sebastiankb mentioned. 
2. Also we use `"mqv:commandCode":8` instead of `"mqv:commandCode":SUBSCRIBE` .

I think that the first part is clear whereas the second one needs discussion

**Comment by egekorkan** [comment]
In the telco we said that we prefer the english word (e.g. SUBSCRIBE) instead of numbers (e.g. 8). @mjkoster any opinions?

**Comment by egekorkan** [comment]
In the 30.08.2019 telco, @mjkoster mentioned that the first part of the issue might be due the new MQTT spec.
Second part is due to the fact that MQTT header uses these numbers so an implementation would need a lookup table to convert `SUBSCRIBE` to `8` but a check for the integer would be needed anyways.
More discussion needed for the second part.

**Comment by mjkoster** [comment]
It looks like it was always called Control Packet type in the MQTT documentation so we could go with that in the official vocabulary.

As an author of TDs, I find it easier to remember the string than the number for the type identifiers, e.g. "SUBSCRIBE" is easier to use than "8"

**Comment by egekorkan** [comment]
Fixed in #79

**Comment by hspaay** [comment]
Apologies if this is thread is obsolete and I'm asking in the wrong place.

@egekorkan the documentation here: 'https://www.w3.org/TR/wot-binding-templates/#action-bindings' uses the term ''controlPacketValue", while the [MQTT specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718021) uses 'control packet type'. 

The Wot binding specification hasn't changed in a few years so I'm wondering what is the correct term to use.
