### ISSUE TITLE
Review Comments - Binding Templates - W3C Editor's Draft 22 December 2019

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-binding-templates#87]
First of all I would like to say that I do not see any blocking issue. I just would like to propose some updates that fix minor things or simplify the document.

I hope the comments are useful.

### ReSpec warnings

* Document uses RFC2119 keywords but lacks a conformance section. Please add a `<section id="conformance">`.

### 1.2 Media Types

"Correct indication of Media Types enable"
-->
"Correct indication of Media Types enables" 

### 3.1.1 Payload Structure

I would find it more intuitive that a given payload and the according DataSchema would be next to each other

Example1 | DataSchema1

Example2 | DataSchema2 

This makes the relation clearer and also gets rid of the references such as "For the Simple Payload in Example 1 above, the DataSchema element would be structured as follows: "

### 3.1.3 XML Schema Binding

"In the previous section, examples showed what data whose value type is described using the type system look like when serialized to XML in parallel to corresponding JSON serializations."

Is this statement really true? The previous section showed examples whose value type is described using the type system in JSON.
No mentioning of XML in previous section..

### 3.1.3.1 Object Definition to XML Schema

I wonder whether we can get rid of the differentation of ananymous vs named constructs for object/array. The only difference in the XML snippets is whether it is wrapped in yet another XML element but the concept remains the same.

@takuki, what do you think?

### 3.2.2 Content Types

I know we do have the same differentations, terms and use of content type in the TD document but "content type" is used exchangeable with "media type"
e.g., we say "media type application/ocf+cbor" and 2 paragraphs later we have "content type is application/xml"

To me the right term is "media type" and content type is used in HTTP.

### 3.2.3 Protocol Methods and Options

"POST may be used for writing a Property value in one platforms"
->
"POST may be used for writing a Property value in one platform"

"http header options"
-->
"HTTP header options"

"using http"
-->
"using HTTP"

### A. Example Sequences of Interaction Affordances

"would only effect"
-->
"would only affect"

### General
Sometimes I was not sure why some terms are capitalized (e.g., "Platform" vs "platform" in other places)

**Comment by egekorkan** [comment]
Fixed in PR #88:
- ReSpec warning
- 1.2
- 3.2.3
- A
- Platform vs platform (need more examples)

**Comment by egekorkan** [comment]
Regarding content type vs media type, I realized that I am not confident enough to provide an answer. Can be discussed in the call of 10.01.2020

**Comment by egekorkan** [comment]
All the mentioned issues are fixed in #88 and I have put you @danielpeintner as a reviewer. Please comment if it is OK :)

**Comment by egekorkan** [comment]
Changes are available in the latest editor's draft. Please close the issue if you think it is good now @danielpeintner
