### ISSUE TITLE
Use "Consumer/Thing" rather than "WoT Client/Server"

### ISSUE THREAD

**Issue by k-toumura** [w3c/wot-binding-templates#89]
On latest architecture document, we use "Consumer" and "Thing" rather than "WoT Client" and "WoT Server". ([6.1  Overvew](https://www.w3.org/TR/wot-architecture/#sec-architecture-overview))

There are several sentence which uses "(WoT) Client/Server" to describe "Consumer/Thing".
- [1.3 Payload Structure](https://w3c.github.io/wot-binding-templates/#payload-structure-0)
  - "Data ... need to be understood by clients" -> "Data ... need to be understood by Consumer"
- [1.4 Data Types and Value Constraints](https://w3c.github.io/wot-binding-templates/#data-types-and-value-constraints)
  - "the system-specific representation on server and client is not relevant for interoperability" ->  
"the system-specific representation on Thing and Consumer is not relevant for interoperability" 
- [3.1 Data Schema](https://w3c.github.io/wot-binding-templates/#sec-data-schema)
  - "... that are passed between client and server during interactions" -> "... that are passed between Consumer and Thing during interactions"
- [3.1.2 Data Types and value constrains](https://w3c.github.io/wot-binding-templates/#data-types-constraints)
  - "clients should follow the data schemas strictly" -> "Consumer should follow the data schemas strictly"
  - "This means that a client sending the payload ..." -> "This means that a Consumer sending the payload ..."
- [3.2 Forms Element](https://w3c.github.io/wot-binding-templates/#form-element)
  - "... between the client and server for the interaction" -> "... between the Consumer and Thing for the interaction"
- [3.2.1 Operation Types](https://w3c.github.io/wot-binding-templates/#operation-types)
   - "...allows the client to select" - > "... allows the Consumer to select"
- [5.  Examples of Thing Descriptions including protocol bindings](https://w3c.github.io/wot-binding-templates/#binding-examples)
  - "... instructs the client ..." -> "... instructs the Consumer ..."
- [A. Example Sequences of Interaction Affordances](https://w3c.github.io/wot-binding-templates/#appendix-example-sequences)
  - Many occurrences in both text and figures.

(There are words "client" in [4.3.3.2 MQTT Default Vocabulary Terms](https://w3c.github.io/wot-binding-templates/#mqtt-default-vocabulary-terms), and "server" in [3.2.3 Protocol Methods and Options](https://w3c.github.io/wot-binding-templates/#protocol-methods-options), but this describes a role in MQTT and HTTP respectively, so this is no problem.)

**Comment by egekorkan** [comment]
All the mentioned issues are fixed in #88 and I have put you @k-toumura as a reviewer. Please comment if it is OK :)

**Comment by egekorkan** [comment]
Changes are available in the latest editor's draft. Please close the issue if you think it is good now @k-toumura

**Comment by k-toumura** [comment]
Looks good for me.  Thank you for your changes.
