### ISSUE TITLE
CSS sizing properties typo?

### ISSUE THREAD

**Issue by Zurc** [w3c/wot-binding-templates#90]
Hi, 

Not sure if this is the best place to write about this issue. 
I was reading about CSS sizing properties on the [draft](https://drafts.csswg.org/css-sizing-3/#width-height-keywords)

on the point 3.2, on the max-content section it says: 'Use the min-content size in the relevant axis...'

should it be 'Use the **max-content** size...' instead?

**Comment by egekorkan** [comment]
Hi,
I think you are in the wrong repository, this for the work on Web of Things standards. You should check the [issue page of css working group](https://github.com/w3c/csswg-drafts/issues)

**Comment by egekorkan** [comment]
Given no further comments and the wrong repository, I am closing this issue.
