### ISSUE TITLE
Create RDF representations of CoAP and MQTT vocabulary

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-binding-templates#93]
Currently, we cannot reference to the CoAP and MQTT vocabulary from the context like it is possible for HTTP. @sebastiankb mentioned that we should contact the community of these protocols to get help but we might also want to start a bit, at least describing the basic features we are using. I would start by looking at the [HTTP in RDF](https://www.w3.org/TR/HTTP-in-RDF10/). @vcharpenay would you have other suggestions?

**Comment by sebastiankb** [comment]
We should involve @ektrah for CoAP.

**Comment by takuki** [comment]
During April 3rd Binding Templates teleconference (see minutes [here](https://www.w3.org/2020/04/03-wot-td-minutes.html)), the following arguments were made.

- New repository can be created for CoAP and MQTT vocabulary development.
  - A new process within W3C (evergreen process) is available.
  - We can also start development in Binding Templates document.
- We should solicit help from someone from MQTT community.

**Comment by mmccool** [comment]
Discussion in main call 2020.04.08
- Need to define use cases to show this applies to more WoT TDs; eg may apply to OCF, OpenAPI, ODM, etc.  Also may help formalize API management in some of these, eg. MQTT.
- We can publish as a WG Note for now, but collaborate with IETF and Oasis for the next level of standardization (if appropriate)

**Comment by egekorkan** [comment]
In the call of 17.04, we have decided to change the coap vocabulary to include the methodName as well as methodCode but keep using the methodName in the TDs.
For the MQTT vocabulary, we will create the vocabulary to be used in the TDs and not model all the features of MQTT.

**Comment by sebastiankb** [comment]
Thanks to @vcharpenay 

the first inits files are available here https://github.com/w3c/wot-binding-templates/tree/master/ontology

**Comment by vcharpenay** [comment]
@ashimura here is some redirection to set up on w3.org, as discussed in today's TD meeting:

with header `Accept: text/turtle`:
 - https://www.w3.org/2019/wot/coap → https://w3c.github.io/wot-binding-templates/ontology/coap.ttl
 - https://www.w3.org/2019/wot/mqtt → https://w3c.github.io/wot-binding-templates/ontology/mqtt.ttl

otherwise: 
 - https://www.w3.org/2019/wot/coap → https://w3c.github.io/wot-binding-templates/ontology/coap.html
 - https://www.w3.org/2019/wot/mqtt → https://w3c.github.io/wot-binding-templates/ontology/mqtt.html

**Comment by egekorkan** [comment]
This issue will only track the MQTT RDF that is in works at #156 

The CoAP RDF is already tracked at https://github.com/w3c/wot-binding-templates/issues/97

**Comment by egekorkan** [comment]
Call of of 02.11, the group has agreed to close
