### ISSUE TITLE
Errors in examples 

### ISSUE THREAD

**Issue by fgrape** [w3c/wot-binding-templates#94]
In [document published 30 January 2020](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/)

I noticed that you are trying to reduce cognitive load for me as a reader by keeping the property names consistent for all objects with the same structure throughout the entire document, this issue is to improve the consistency of object structures.

### [4.1.3.2 Array Schema to XML Schema](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/#mapping-to-xml-schema-array)
The tag on line 4 in [Example 13](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/#example-13-xml-schema-mapping-of-the-above-json-schema-with-an-anonymous-array) and line 8 in [Example 14](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/#example-14-xml-schema-mapping-of-the-above-json-schema-with-a-non-anonymous-array) that defines the schema for elements in the array specifies the name _double_ when it should be _number_ to match [Example 19](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/#example-19-corresponding-xml-payload-for-the-previous-json-payload)

```` XML
EXAMPLE 13

<xs:element name="array" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="double" minOccurs="3" maxOccurs="3">
                <xs:simpleType name="minInclusive">
                    <xs:restriction base="xs:double">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="2047"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
````
````XML
EXAMPLE 19

<array>
  <number>520</number>
  <number>184</number>
  <number>1314</number>
</array>
````

### [4.2.2 Content Types](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/#content-types)
[Example 16](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/#example-16-json-payload-of-object-type-for-specifying-the-desired-brightness-and-flashing-frequency-of-a-lamp) and [Example 17](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/#example-17-corresponding-xml-payload-for-the-previous-json-payload) appears to be inconsistent as the JSON has two properties _brightness_ and _frequency_ and the corresponding XML has two tags _id_ and _frequency_, surely the XML tags should be _brightness_ and _frequency_?

```` JSON
EXAMPLE 16

{
  "brightness": 200,
  "frequency": "fast"
}
````

```` XML
EXAMPLE 17

<object>
  <id>
    <integer>200</integer>
  </id>
  <frequency>
    <string>fast</string>
  </frequency>
</object>
````

These examples are clearly example payloads based on the schemas in [Example 9](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/#example-9-json-schema-description-of-the-required-json-object), [10](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/#example-10-xml-schema-mapping-of-the-above-json-schema-with-an-anonymous-object) and [11](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/#example-11-xml-schema-mapping-of-the-above-json-schema-with-a-non-anonymous-object) (using properties _id_ and _name_) but with new property names for the JSON and partially new tags for the XML payload. 

### Minor JSON formatting errors

- In [Example 27](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/#example-27-td-with-a-simple-payload) there is a comma missing after the CoAP vocabulary link, resulting in weird syntax highlighting
- In [Example 28](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/#example-28-td-with-protocol-options-and-complex-payload) the same comma is missing. There also seems to be one too many curly braces at the end when analyzing with JSONLint (or some other problem), causing problems with the syntax highlighting for the entire object.

**Comment by egekorkan** [comment]
Thank you for the issue and for reading through the specification. 
- The brightness is indeed an error (probably copy pasting). Fixing it now
- A number type in JSON Schema corresponds either to xs:double or xs:decimal. I am not sure if xs:number is a valid type in XML Schema. @takuki any opinion on this?
- I have fixed the two minor mistakes.

The changes are tracked in PR #95

**Comment by fgrape** [comment]
#### Regarding the xs:double, xs:decimal etc
As I interpret binding templates they try to map different ways of sending application data back and forth. And you won't always have a perfect match for data types since JavaScript still only has one type for numbers, Number (double precision floats), where XML has 14(!) different types. So doing that binding to _choose the most appropriate type_ for a specific application data message is up to the one actually creating the binding template for a specific device, right?

My point regarding the array XML schema was that it sets the name to _double_ but then in the array in the example that name is _number_. I'm hardly know anything about XML-schemas but the name can be separate from the type see example from [W3Schools](https://www.w3schools.com/xml/schema_dtypes_numeric.asp), so the name should be number but the type should still be xs:double as it is the most appropriate binding if the device is expecting a double precision float

```` XML
<xs:element name="price" type="xs:decimal"/>

<price>999.50</price>
````

**Comment by danielpeintner** [comment]
FYI: The general idea is to use the JSON <--> XML mapping from EXI4JSON. See [JSON number](https://www.w3.org/TR/exi-for-json/#N66133).

In EXI4JSON a number is usually represented with xsd:double while it is possible to improve the representation by using for example xsd:integer if we deal with an integral number.

Having said that, EXI4JSON does not allow you to represent any XML data in JSON. It is does allow you to represent any JSON data in EXI(XML) efficiently and consistently transform it back to JSON.

Hope this helps.

**Comment by egekorkan** [comment]
They are now included in the specification's editor's draft. I would propose closing this issue.

**Comment by RoboPhred** [comment]
Example 28 now places the 'forms' for the 'switchOff' action outside of the 'switchOff' action, in the 'actions' property.  By its tab order, it would appear to be inside 'switchOff', but an extra closing bracket ends the object early:
```json
"switchOff": {
      "@type": ["iot:SwitchOffAction"],
      "input": {
            "type": "boolean",
            "const": false
        } // This closes input
      }, // This closes switchOff
      "forms": [ // forms is now in the actions property
        {
          "href": "/example/light/currentswitch",
          "contentType": "application/json",
          "op": ["invokeaction"],
          "htv:methodName": "POST"
        }
      ]
    }
```

You can confirm this by running the entire example through a json parser.  You will find `actions.switchOff` has no `forms` property, but a `forms` property will exist at `actions.forms`
